### ISSUE TITLE
Unable to create TFS workspace in Jetbrains Rider

### ISSUE THREAD

**Issue by DPShillcock** [microsoft/azure-devops-intellij#180]
I am able to authenticate with TFS within Jetbrains Rider, however when I attempt to create a new workspace I get the following error:

`com.microsoft.alm.plugin.external.exceptions.ToolException: KEY_TF_EXE_NOT_FOUND
	at com.microsoft.alm.plugin.external.tools.TfTool.getValidLocation(TfTool.java:77)
	at com.microsoft.alm.plugin.external.commands.Command.run(Command.java:139)
	at com.microsoft.alm.plugin.external.commands.Command.runSynchronously(Command.java:216)
	at com.microsoft.alm.plugin.idea.tfvc.ui.checkout.TfvcCheckoutModel$1.run(TfvcCheckoutModel.java:80)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by julia-vaseva** [comment]
@DPShillcock Did you set the path to TF.cmd in "File | Settings | Version Control | TFVC"? Please take a look at this guide: https://rider-support.jetbrains.com/hc/en-us/articles/115001583664-Wrong-path-to-TF-executable

**Comment by ForNeVeR** [comment]
Probably you should install and configure the TF Everywhere client. Closing, because we've improved the TF client installation a bit since then. Thanks for reporting!
