### ISSUE TITLE
Checkout project gives CreateWorkspaceCommand fatal error

### ISSUE THREAD

**Issue by tripleacoder** [Microsoft/azure-devops-intellij#187]
I am using the VSTS plugin with Android Studio. 
I have a TFVC repo on Azure DevOps. The repo contains some source code.
From the start menu, I choose "Checkout project", then select the repo. When I click on Create Workspace, I get this:

IDE Fatal Errors
java.lang.RuntimeException: The syntax of the command is incorrect.

	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:405)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.throwIfError(CreateWorkspaceCommand.java:91)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:73)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:22)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:171)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)

**Comment by tripleacoder** [comment]
The Azure DevOps project name contains a space. Could that be the reason for the syntax error?

**Comment by tripleacoder** [comment]
When I click on Manage workspaces I see an organization that has been deleted  from Azure DevOps. Under it are 4 workspaces referring to projects that don't exist anymore. Workspace Comment for all of them is "Workspace created through IntelliJ".

It would be nice to delete these to see if that would solve my workspace problem. However, all the command buttons to the right throw errors when I click them.

**Comment by tripleacoder** [comment]
Reload workspaces gives this error:

getAuthenticationInfoAsync failed

com.microsoft.alm.plugin.exceptions.TeamServicesException: KEY_VSO_AUTH_FAILED
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfoAsync(VsoAuthInfoProvider.java:98)
	at com.microsoft.alm.plugin.authentication.VsoAuthenticationProvider.authenticateAsync(VsoAuthenticationProvider.java:69)
	at com.microsoft.alm.plugin.authentication.AuthHelper.getAuthenticationInfoSynchronously(AuthHelper.java:59)
	at com.microsoft.alm.plugin.context.ServerContextManager.getAuthenticationInfo(ServerContextManager.java:476)
	at com.microsoft.alm.plugin.idea.tfvc.ui.management.ManageWorkspacesModel.reloadWorkspaces(ManageWorkspacesModel.java:89)
	at com.microsoft.alm.plugin.idea.tfvc.ui.management.ManageWorkspacesModel$1.run(ManageWorkspacesModel.java:67)
	at com.intellij.vcsUtil.VcsUtil.lambda$runVcsProcessWithProgress$10(VcsUtil.java:410)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:247)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:574)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by alanee1996** [comment]
i having the same issue

**Comment by ForNeVeR** [comment]
@alanee1996, hello. This thread contains descriptions of two separate issues. Which one are you experiencing?
