### ISSUE TITLE
Any action cause KEY_TF_AUTH_FAIL error

### ISSUE THREAD

**Issue by GrushinEgor** [microsoft/azure-devops-intellij#256]
Hello. I'm getting KEY_TF_AUTH_FAIL error when I'm trying to make any TFVS action using JetBrains Webstorm or JetBrains Rider.

This error causes both on Windows and MacOS, on several different machines.

I've tried [TFS Plugin](https://plugins.jetbrains.com/plugin/4578-tfs/) with the same tfvs repository and it has worked. However it has thrown 401 error and I've been able to fix it with next java flags:
-Dorg.jetbrains.tfsIntegration.webservice.auth.ntlm.message1flags=0x00088207
-Dorg.jetbrains.tfsIntegration.webservice.auth.ntlm.message3flags=0x00088205

Now, I want to use your plugin, I still have java flags described above - how can I fix this error?

idea.log: 
```
2019-11-20 20:56:28,468 [ 165702]   INFO - in.idea.common.utils.VcsHelper - getRepositoryContext: cache miss: /Users/egorgrushin/projects/Portal/Src/Portal.Web.SPA 
2019-11-20 20:56:28,468 [ 165702]   INFO - lugin.external.ToolRunnerCache - getRunningToolRunner: toolLocation={0} 
2019-11-20 20:56:28,468 [ 165702]   INFO - lugin.external.ToolRunnerCache - getRunningToolRunner: fast version - 14.134.0.201804261732 
2019-11-20 20:56:28,468 [ 165702]   INFO - lugin.external.ToolRunnerCache - getRunningToolRunner: key=/usr/local/cellar/tee-clc/14.134.0/bin/tf|/users/egorgrushin/projects/portal/src/portal.web.spa 
2019-11-20 20:56:28,468 [ 165702]   INFO - alm.plugin.external.ToolRunner - sendArgsViaStandardInput: proceedWithArgs: workfold -noprompt ******** 
2019-11-20 20:56:28,468 [ 165702]   INFO - lugin.external.ToolRunnerCache - updateCachedInstance: caching a new runner: key=/usr/local/cellar/tee-clc/14.134.0/bin/tf|/users/egorgrushin/projects/portal/src/portal.web.spa 
2019-11-20 20:56:28,468 [ 165702]   INFO - alm.plugin.external.ToolRunner - ToolRunner.start: toolLocation = /usr/local/Cellar/tee-clc/14.134.0/bin/tf 
2019-11-20 20:56:28,468 [ 165702]   INFO - alm.plugin.external.ToolRunner - ToolRunner.start: workingDirectory = /Users/egorgrushin/projects/Portal/Src/Portal.Web.SPA 
2019-11-20 20:56:28,468 [ 165702]   INFO - alm.plugin.external.ToolRunner - arguments: @ 
2019-11-20 20:56:28,865 [ 166099]   INFO - ugin.external.commands.Command - CMD: =============================================================================== 
2019-11-20 20:56:28,865 [ 166099]   INFO - ugin.external.commands.Command - CMD: Workspace:  Foris 
2019-11-20 20:56:28,865 [ 166099]   INFO - ugin.external.commands.Command - CMD: Collection: https://tfs.mtsit.com/sts/ 
2019-11-20 20:56:36,361 [ 173595]   INFO - ugin.external.commands.Command - ERROR: An error occurred: Access denied connecting to TFS server https://tfs.mtsit.com/ (authenticating as username) 
2019-11-20 20:56:36,392 [ 173626]   WARN - .commands.FindWorkspaceCommand - Authentication exception hit when running 'tf workfold' 
2019-11-20 20:56:36,392 [ 173626]   WARN - ugin.external.commands.Command - CMD: parsing output failed 
com.microsoft.alm.plugin.external.exceptions.ToolAuthenticationException: KEY_TF_AUTH_FAIL
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.throwIfError(FindWorkspaceCommand.java:130)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:88)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:24)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)
2019-11-20 20:56:36,392 [ 173626]   WARN - ugin.external.commands.Command - Error: com.microsoft.alm.plugin.external.exceptions.ToolAuthenticationException: KEY_TF_AUTH_FAIL
Sync stack trace: java.base/java.lang.Thread.getStackTrace(Thread.java:1606)
    at com.microsoft.alm.plugin.external.commands.Command.runSynchronously(Command.java:243)
    at com.microsoft.alm.plugin.idea.common.utils.VcsHelper.getRepositoryContext(VcsHelper.java:174)
    at com.microsoft.alm.plugin.idea.tfvc.core.TFSVcs.getServerContext(TFSVcs.java:254)
    at com.microsoft.alm.plugin.idea.tfvc.core.TFSHistoryProvider.createSessionFor(TFSHistoryProvider.java:83)
    at com.microsoft.alm.plugin.idea.tfvc.core.TFSHistoryProvider.reportAppendableHistory(TFSHistoryProvider.java:119)
    at com.intellij.openapi.vcs.history.VcsCachingHistory.reportHistory(VcsCachingHistory.java:90)
    at com.intellij.openapi.vcs.history.VcsCachingHistory.access$000(VcsCachingHistory.java:31)
    at com.intellij.openapi.vcs.history.VcsCachingHistory$1.run(VcsCachingHistory.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
    at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834) 
2019-11-20 20:56:36,393 [ 173627]   INFO - ugin.external.commands.Command - 7.924708397 sec - elapsed time for workfold -noprompt ******** 
2019-11-20 20:56:36,393 [ 173627]   WARN - in.idea.common.utils.VcsHelper - Unable to get repository context for the project. 
com.microsoft.alm.plugin.external.exceptions.ToolAuthenticationException: KEY_TF_AUTH_FAIL
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.throwIfError(FindWorkspaceCommand.java:130)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:88)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:24)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)
2019-11-20 20:56:36,393 [ 173627]   INFO - in.idea.common.utils.VcsHelper - getRepositoryContext: We couldn't determine the VCS provider, so returning null. 
2019-11-20 20:56:36,393 [ 173627]   INFO - m.plugin.idea.tfvc.core.TFSVcs - TFSVcs.getServerContext repositoryContext is null: true 

```

**Comment by ForNeVeR** [comment]
Hello. This plugin doesn't make any use of the flags you've mentioned.

Could you please explain, which particular circumstances lead you to changing these flags? Does your server use some unusual or custom NTLM auth scheme?

**Comment by GrushinEgor** [comment]
@ForNeVeR thank you for your answer!

No, our server doesn't use any custom flags. 

Now question is why it gets **KEY_TF_AUTH_FAIL** error from plugin, but doesn't from cmd?

**Comment by ForNeVeR** [comment]
Could you please explain further? What do you mean by "it gets **KEY_TF_AUTH_FAIL** error from plugin, but doesn't from cmd"?

Are you trying to run something (e.g. a TF client) from cmd, and it works with your server? You havent't mentioned it previously, and that's very important information. Please elaborate.

**Comment by GrushinEgor** [comment]
I'm sorry, It was in my head, but not in text.

I'm using the same TF client (TEE-CLC on MacOS) as this plugin requires. From terminal it works great, from plugin it throws an error I described above. 

Also, TF plugin uses  credentials stored in my Mac Keychain so it authorizes silently

**Comment by ForNeVeR** [comment]
That's interesting. Let's proceed with the diagnostics. First of all, I'd like to know how you determine that the TF command-line client works. Are you running some particular command in your terminal? Is it the same command that you're seing in the IDE logs? Does it ask you for authentication information every time you enter a command? Please show this command.

I'm investigating another similar case right now, but we haven't yet understood what's wrong with the way we're running the TF client.

**Comment by ForNeVeR** [comment]
`FindWorkspaceCommand` throwing an authentication error is a sure sign of a server workspace being involved. Could you please check if the workspace in question is a server one? How did you get one on macOS?

**Comment by sashka304** [comment]
Hello, I have the same error. I had local workspace, and it was ok... but when I have chaged to server workspace error appared.

**Comment by ForNeVeR** [comment]
We don't support the server workspaces yet, but we're very close to enabilng the support. Feel free to watch over #325 (there's already an open PR, #360).

**Comment by AbhayKasturia** [comment]
Hi Team,

We are facing a similar issue. We have a local workspace that is showing up in the command 'tf.cmd workspaces'. We open a project from that path and select 'Enable Version Control Integration' and then select TFVS, we get the same error:
https://pastebin.com/3WDU7v63

Is this something that is already fixed?

Regards

**Comment by ForNeVeR** [comment]
@AbhayKasturia, is the reactive client enabled in your TFVC settings? Could you try disabling it? AFAIK it doesn't support any custom certificates yet, due to technical reasons.

**Comment by AbhayKasturia** [comment]
Hi @ForNeVeR , seems like it is trying to run the 'tf workfold' command and is failing when authenticating. We tried running this command with the TEE-CLC in cmd and it ran fine. We are using PAT for authentication and not a username-password. 

https://pastebin.com/Sb7ih8K6

**Comment by ForNeVeR** [comment]
What is "PAT"? Are you able to make `tf workfold` use this?

**Comment by ForNeVeR** [comment]
Usually, `tf workfold` will only ask for authentication when encountering a server workspace. Do you use a server workspace?

**Comment by AbhayKasturia** [comment]
Hi @ForNeVeR, 

We have a server workspace. And yes we are using Personal Access Token for any authentication to the server. 

We have a workspace that is already setup. Because we also use Visual Studio for development. We want to use the same workspace for IntelliJ. The exact steps to replicate:

1. Open a project from the workspace directory in IntelliJ.
2. Open the VCS operation pop up using Alt+`
3. Select Enable Version Control Integration
4. Select TFVC in the options

As soon as we do this we see an error occurs. The error message is the same as sent before. 

We have tried with and without the reactive client, we get the same error.

Regards,

**Comment by ForNeVeR** [comment]
@AbhayKasturia, thanks for your answer!

Right now, the released version of the plugin doesn't support the server workspaces at all, so this error is to be expected.

We're working on server workspace support; the plugin build is already going through the second review round of our QA team. Hopefully, it will be released next week.

**Comment by AbhayKasturia** [comment]
My bad. I just checked once again. It is a local workspace. 

![image](https://user-images.githubusercontent.com/19328904/90329812-c5262300-df75-11ea-9bd4-876e6307e639.png)

**Comment by ForNeVeR** [comment]
This is very strange. Could you reproduce this behavior with `tf.cmd workfold` being called from a terminal window? It should be called from a directory containing your workspace.

**Comment by AbhayKasturia** [comment]
@ForNeVeR, Nope. On running the 'tf.cmd workfold' command in the project directory, it runs fine and is able to authenticate and run. Even after the 'tf workfold' command was running from cmd. It still is throwing the same error in the plugin.

Point to be noted here: A couple of days back, running the 'tf workfold' command failed from cmd. It used to ask for username and password and when we tried logging in with our current AD username and password, it failed. 

Here were the steps we followed to fix that:
1. Logged into our Azure Dev Ops account using our  AD credentials.
2. Created a PAT for the Azure DevOps account
3. Ran the following commands from cmd:
     set TF_AUTO_SAVE_CREDENTIALS=1
     tf.cmd workfold
     username: <Entered the PAT created in Step 2>

After this, it never asked for authentication again. 

What my assumption is that when plugin tries to run the 'tf workfold' command, it is trying to login with a username that is returning an unauthorized error. It should be using the PAT creds that is already stored by TF, but is not using them. 

Let me know your thoughts on this.

Regards,

**Comment by ForNeVeR** [comment]
I still don't understand how to make `tf workfold` to require authentication for a local workspace. That's why the issue is still not fixed: we have no way (yet) of reproducing it :(

Plugin usually passes `-login username,pw` (**literally** [a string "username,pw"](https://github.com/microsoft/azure-devops-intellij/blob/1cdaf0aab461096ba5e0f25ce348d1bafe6b2ff7/plugin/src/com/microsoft/alm/plugin/external/commands/FindWorkspaceCommand.java#L93)) for a local workspace, this could be a potential reason for the issue. But it is still unclear why couldn't `workfold` work in such case; usually it does work.

We have changed the way it works for a server workspaces a bit, so it's possible it will start working in your case after the new release.

**Comment by AbhayKasturia** [comment]
Hi @ForNeVeR, I might have figured out the exact issue. This is the command that the plugin tries to run. 

C:\Users\<username>\Documents\TEE-CLC-14.134.0\TEE-CLC-14.134.0\tf.cmd workfold -noprompt

This by default tries to log in using the username(abhay.kasturia@philips.com) and not the PAT.

![image](https://user-images.githubusercontent.com/19328904/90439131-049e5d80-e0a3-11ea-8e33-4144a841a72c.png)

**Comment by AbhayKasturia** [comment]
We figured the error out. On a few systems for some reason, the workspace was being read as a 'Server workspace'. After changing the workspace to be local, it worked fine. Thank you for all your help.

**Comment by ForNeVeR** [comment]
I'm glad the issue has been resolved. For a local workspace, it shouldn't be important which username is used for the `workfold` command, because it is ignored by the command (but it is still _required_ for some crazy reason). I think that in next plugin release we'll be able to handle this situation better.

Could you please clarify, how this (detecting a local workspace as a server one) happened?

**Comment by ForNeVeR** [comment]
After investigation in #401, we've been able to find a possible reason for the issue, and a workaround that fixed the issue for one user.

The plugin may sometimes (always?) remember the credentials for custom TFVC servers too well, and won't ask them again even if the server reports they're wrong.

The workaround for such cases is the following:
1. Open the **Version Control → Azure DevOps Services / TFS** IDE settings page
2. Delete all the credentials from the page
3. Restart the IDE
4. Open the **Appearance & Behavior → System Settings → Passwords** IDE settings page
5. Press the gear icon on the right, and choose the **Clear** action:
   ![image](https://user-images.githubusercontent.com/92793/94115513-09a9b600-fe74-11ea-85b1-2e16311e4eaa.png)

This will make the IDE to definitely forget the password it was remembering for your server, and it should save the new, the right one.

This is a bug in how we handle tool authentication errors (we never flush the credential storage when getting the authentication errors), and should be fixed in the plugin itself.
