### ISSUE TITLE
Exception java.lang.NoSuchFieldError: myAddedFiles in TFSFileListener.executeAdd

### ISSUE THREAD

**Issue by yasanches** [microsoft/azure-devops-intellij#263]
It seems there is problem due update in VcsVFSListener. The new internal class StateProcessor was added into VcsVFSListener. So the field like myAddedFiles was replaced into it new  internal class, but the code in TFSFileListener continues to reference to this field as it still belongs to VcsVFSListener. As a consequence we have an exception 

java.lang.NoSuchFieldError: myAddedFiles
	at com.microsoft.alm.plugin.idea.tfvc.core.TFSFileListener.executeAdd(TFSFileListener.java:76)
	at com.intellij.openapi.vcs.VcsVFSListener$StateProcessor.process(VcsVFSListener.java:207)
	at com.intellij.openapi.vcs.VcsVFSListener$StateProcessor.access$1300(VcsVFSListener.java:86)
	at com.intellij.openapi.vcs.VcsVFSListener$MyCommandAdapter.lambda$commandFinished$0(VcsVFSListener.java:686)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:247)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$4(ApplicationImpl.java:441)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:209)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ForNeVeR** [comment]
Thanks for the report! We've already fixed this in https://github.com/microsoft/azure-devops-intellij/pull/258. A plugin update will be released soon.

**Comment by yasanches** [comment]
Thanks. Look forward to that.
