### ISSUE TITLE
Pull Request Created modal points to wrong URL #277

### ISSUE THREAD

**Issue by baltuonis** [microsoft/azure-devops-intellij#280]
Repro:

1. Create a pull request (using Jetbrains Rider Azure action)
2. Click link "Open pull request XXXX to add reviewers or associate work items."
3. Link points to https://XXXXX@dev.azure.com/XXXXXX/xxxx/_git/project/pullrequest/3934#view=discussion
4. Displays blank page, because of `#view=discussion` part. 

Fix:

Do not add `#view=discussion` part to the URL

**Comment by ForNeVeR** [comment]
Honestly, it looks like a bug in the Azure DevOps web interface. Browser console holds the following:

```
Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://dev.azure.com/sofiabyzova/MyTestTFSProjectYa/_git/MyTestTFSProjectYa/pullrequest/1#view=discussion' cannot be created in a document with origin 'https://dev.azure.com' and URL 'https://sofiabyzova@dev.azure.com/sofiabyzova/MyTestTFSProjectYa/_git/MyTestTFSProjectYa/pullrequest/1#view=discussion'.
    at serviceFactory._setState (https://cdn.vsassets.io/ext/ms.vss-web/platform-content/ms.vss-web.platform-content.es6.3b7Is3GGQSCsUDSl.min.js:1:78582)
    at serviceFactory.replaceState (https://cdn.vsassets.io/ext/ms.vss-web/platform-content/ms.vss-web.platform-content.es6.3b7Is3GGQSCsUDSl.min.js:1:76698)
    at serviceFactory._serviceStart (https://cdn.vsassets.io/ext/ms.vss-web/platform-content/ms.vss-web.platform-content.es6.3b7Is3GGQSCsUDSl.min.js:1:76533)
    at Object._loadService (https://cdn.vsassets.io/ext/ms.vss-web/platform-content/ms.vss-web.platform-content.es6.3b7Is3GGQSCsUDSl.min.js:1:9004)
    at Object.getService (https://cdn.vsassets.io/ext/ms.vss-web/platform-content/ms.vss-web.platform-content.es6.3b7Is3GGQSCsUDSl.min.js:1:8285)
    at HTMLDocument.<anonymous> (https://cdn.vsassets.io/ext/ms.vss-web/platform-content/ms.vss-web.platform-content.es6.3b7Is3GGQSCsUDSl.min.js:1:7074)
```

But, I can't see why we need `#view=discussion` now. It looks like that "discussion" tab was merged with the overview, and it is now shown by default.

**Comment by ForNeVeR** [comment]
Superseded by #283. Thanks for help!
