### ISSUE TITLE
Error when creating workspace if the user password contains non-cmd-friendly characters

### ISSUE THREAD

**Issue by kawazoe** [microsoft/azure-devops-intellij#323]
_(Edited by F.: please see the steps to reproduce and workaround [below](https://github.com/microsoft/azure-devops-intellij/issues/323#issuecomment-613826895).)_

I tried to use this plugin for the first time today and trying to create my local workspace failed with a crash. This is trying to connect to an organisation tfs server.

### Repro Steps

1) Open any IntelliJ based IDS (I used Rider for this)
2) On the welcome screen, click on "Get from Version Control"
3) Select "Respository URL"
4) From the "Version control" drop down, choose "Azure DevOps TFVC"
5) Click "Clone"
6) In the "Checkout from Azure DevOps Services", select the "Team Foundation Server" tab
7) * Enter your server URL
8) Select a Repository and keep other default settings
9) * Click "Create Workspace"

* During this process, I had to accept the server's certificate.

### What should happen

The workspace is mapped on my machine and files starts to download into the specified folder. If the "Edit workspace" checkbox is checked, I would expect to chose what files will get downloaded.

### What happened instead

After a bit of loading, the window closes bringing me back to the welcome screen. The Event Log icon on the bottom right appears red. Clicking on it shows an "IDE Fatal Error" with the following stack trace:

```
java.lang.RuntimeException: An error occurred: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:423)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.throwIfError(CreateWorkspaceCommand.java:91)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:73)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:22)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)
```

**Comment by ForNeVeR** [comment]
Hello. Could you please clarify, how exactly are you trying to create a local workspace? Exact steps to you're taking to get this error? Thanks in advance.

**Comment by kawazoe** [comment]
@ForNeVeR I edited the initial post to add more info

**Comment by ForNeVeR** [comment]
Thanks for help. Do you use on-premise installation of TFS/Azure DevOps server? In that case, you'll have to install your server's certificate into our JVM (we're working on a fix for that, but for now it's a requirement).

Take a look at [this article](http://blog.majcica.com/2017/01/02/working-with-tfs-in-intellij-idea-via-vsts-plugin/), "Importing the certificate" section.

**Comment by kawazoe** [comment]
Thanks for the link, though I use JetBrains Toolbox so I had to figure out where the tool and certificate store where located. This definitely helped. I assumed that such manipulation would not be required since Rider did request me to authorize the server certificate when connecting to the server.

While this fixes the certs issue, I now get a new interesting error. As it creates the workspace, I get an "Access Denied" fatal error. This is obviously not a credential error since I had to see select a repository already.

I do not know if this has anything to do with the error, but the URL I get in the error does not inclue de "/tfs" path at the end of the URL I used when initially connecting. Trying to access the URL in a browser without this path will indeed trigger a HTTP 403 error.

I already tried to update my credentials in the plugin settings but it didn't changed anything.

**Comment by ForNeVeR** [comment]
Could you please share some logs? Which exact error do you receive (with a stack trace if it's available)?

**Comment by kawazoe** [comment]
I'm afraid there isn't much info in there. The callstack looks like it is properly parsing the server's output. Like I said, the only interesting bit is in the URL as it does not include the path that I specified when connecting to the server which might be a clue of what is going on.

```
java.lang.RuntimeException: An error occurred: Access denied connecting to TFS server https://removed/ (authenticating as REMOVED\REMOVED)

	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:423)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.throwIfError(CreateWorkspaceCommand.java:91)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:73)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:22)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)
```

Like I said previously, trying to access that URL will indeed give me an HTTP 403 error. It will only work if I include the path.

**Comment by ForNeVeR** [comment]
The actual arguments passed to the client should be printed to the logs. Something like this:
```
sendArgsViaStandardInput: proceedWithArgs: workspace -noprompt -collection:http://desktop-i35dvo5/Space Collection ******** -new -location:local My Project_20200409_0 -comment:Workspace created through IntelliJ
```

Could you please check if these arguments contain the proper URL?

**Comment by kawazoe** [comment]
Hmmm, it appears they do. Here's an anonymized version of the log.

```log
2020-04-09 10:45:07,390 | INFO  | RepositoryHelper               | using cached plugin list (updated at 4/9/2020 10:38 AM)
2020-04-09 10:45:10,625 | INFO  | VsoCheckoutPageModel           | Skipping loading contexts in constructor
2020-04-09 10:45:10,625 | INFO  | CheckoutPageModelImpl          | TFS auth info already found so reusing that for loading repos
2020-04-09 10:45:10,625 | INFO  | ServerContextLookupListener    | loadContexts activeOperation with 1 contexts and a scope of PROJECT
2020-04-09 10:45:10,625 | INFO  | ServerContextLookupListener    | loadContexts terminateActiveOperation in state NOT_STARTED
2020-04-09 10:45:10,625 | INFO  | ServerContextLookupListener    | ServerContext operation terminated
2020-04-09 10:45:10,640 | INFO  | ServerContextLookupListener    | ServerContext lookup started
2020-04-09 10:45:11,047 | WARN  | HttpAuthenticator              | NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
2020-04-09 10:45:11,312 | WARN  | HttpAuthenticator              | NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
2020-04-09 10:45:11,515 | WARN  | HttpAuthenticator              | NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
2020-04-09 10:45:11,593 | INFO  | HttpProxyServiceImpl           | useHttpProxy: false
2020-04-09 10:45:12,109 | WARN  | HttpAuthenticator              | NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
2020-04-09 10:45:12,359 | WARN  | HttpAuthenticator              | NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
2020-04-09 10:45:12,422 | INFO  | ServerContextLookupListener    | ServerContext lookup results has error: false
2020-04-09 10:45:12,578 | WARN  | HttpAuthenticator              | NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
2020-04-09 10:45:12,781 | WARN  | HttpAuthenticator              | NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
2020-04-09 10:45:12,828 | INFO  | ServerContextLookupListener    | ServerContext lookup results has error: false
2020-04-09 10:45:12,828 | INFO  | ServerContextLookupListener    | ServerContext lookup completed
2020-04-09 10:45:12,828 | INFO  | ServerContextLookupListener    | ServerContext operation done
2020-04-09 10:45:19,890 | WARN  | HttpAuthenticator              | NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
2020-04-09 10:45:19,953 | WARN  | VstsHttpClient                 | sendRequest error: 404 : Not Found
2020-04-09 10:45:19,953 | INFO  | ServerContextManager           | validateTfvcCollectionUrl: found 404 for url: https://REMOVED/tfs
2020-04-09 10:45:20,109 | WARN  | HttpAuthenticator              | NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
2020-04-09 10:45:20,187 | INFO  | ServerContextManager           | validateTfvcCollectionUrl: validated url: https://REMOVED/tfs/PROJECT
2020-04-09 10:45:20,359 | WARN  | HttpAuthenticator              | NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
2020-04-09 10:45:20,562 | WARN  | HttpAuthenticator              | NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
2020-04-09 10:45:20,781 | WARN  | HttpAuthenticator              | NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
2020-04-09 10:45:21,000 | WARN  | HttpAuthenticator              | NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
2020-04-09 10:45:21,234 | WARN  | HttpAuthenticator              | NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
2020-04-09 10:45:21,281 | INFO  | ServerContextManager           | Validating a TFS server context with a server URI https://REMOVED/tfs
2020-04-09 10:45:21,453 | WARN  | HttpAuthenticator              | NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
2020-04-09 10:45:21,640 | INFO  | ToolRunnerCache                | getRunningToolRunner: toolLocation={0}
2020-04-09 10:45:21,640 | INFO  | ToolRunnerCache                | getRunningToolRunner: slow version - null
2020-04-09 10:45:21,640 | INFO  | ToolRunner                     | ToolRunner.start: toolLocation = C:\TEE-CLC-14.134.0\tf.cmd
2020-04-09 10:45:21,640 | INFO  | ToolRunner                     | ToolRunner.start: workingDirectory = null
2020-04-09 10:45:21,640 | INFO  | ToolRunner                     | arguments: workspace -noprompt -collection:https://REMOVED/tfs/PROJECT ******** -new -location:local rider -comment:Workspace created through IntelliJ
2020-04-09 10:45:21,640 | WARN  | PerformanceWatcher             | UI freezed for 1968ms, details saved to C:\Users\REMOVED\.Rider2019.3\system\log\threadDumps-freeze-20200409-104519-RD-193.6494.48-SocketInputStream.socketRead0-1sec
2020-04-09 10:45:22,172 | WARN  | ProgressIndicatorBase          | This progress indicator is indeterminate, this may lead to visual inconsistency. Please call setIndeterminate(false) before you start progress.
com.microsoft.alm.plugin.idea.common.utils.IdeaHelper$1.run(IdeaHelper.java:64)
2020-04-09 10:45:26,140 | INFO  | Command                        | ERROR: An error occurred: Access denied connecting to TFS server https://REMOVED/ (authenticating as REMOVED\REMOVED)
2020-04-09 10:45:26,203 | WARN  | Command                        | CMD: parsing output failed
java.lang.RuntimeException: An error occurred: Access denied connecting to TFS server https://REMOVED/ (authenticating as REMOVED\REMOVED)

	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:423)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.throwIfError(CreateWorkspaceCommand.java:91)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:73)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:22)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)
2020-04-09 10:45:26,218 | WARN  | Command                        | Error: java.lang.RuntimeException: An error occurred: Access denied connecting to TFS server https://REMOVED/ (authenticating as REMOVED\REMOVED)

Sync stack trace: java.base/java.lang.Thread.getStackTrace(Thread.java:1606)
    at com.microsoft.alm.plugin.external.commands.Command.runSynchronously(Command.java:243)
    at com.microsoft.alm.plugin.idea.tfvc.ui.settings.EULADialog.executeWithGuard(EULADialog.java:226)
    at com.microsoft.alm.plugin.idea.tfvc.ui.checkout.TfvcCheckoutModel$1.run(TfvcCheckoutModel.java:79)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
    at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
    at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
    at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
2020-04-09 10:45:26,218 | INFO  | Command                        | 4.616302765 sec - elapsed time for workspace -noprompt -collection:https://REMOVED/tfs/PROJECT ******** -new -location:local rider -comment:Workspace created through IntelliJ
2020-04-09 10:45:26,218 | WARN  | RiderApplicationLoadListener   | [STDERR] : 4.616302765 sec - elapsed time for workspace -noprompt -collection:https://REMOVED/tfs/PROJECT ******** -new -location:local rider -comment:Workspace created through IntelliJ
2020-04-09 10:45:26,218 | ERROR | Task                           | An error occurred: Access denied connecting to TFS server https://REMOVED/ (authenticating as REMOVED\REMOVED)

java.lang.RuntimeException: An error occurred: Access denied connecting to TFS server https://REMOVED/ (authenticating as REMOVED\REMOVED)

	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:423)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.throwIfError(CreateWorkspaceCommand.java:91)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:73)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:22)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)
2020-04-09 10:45:26,218 | ERROR | Task                           | JetBrains Rider 2019.3.4  Build #RD-193.6494.48
2020-04-09 10:45:26,218 | ERROR | Task                           | JDK: 11.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o
2020-04-09 10:45:26,218 | ERROR | Task                           | OS: Windows Server 2012 R2
2020-04-09 10:45:26,218 | ERROR | Task                           | Plugin to blame: Azure DevOps version: 1.159.0
2020-04-09 10:45:26,218 | ERROR | Task                           | Last Action: Vcs.VcsClone
2020-04-09 10:45:27,093 | INFO  | RepositoryHelper               | using cached plugin list (updated at 4/9/2020 10:38 AM)
2020-04-09 10:45:27,781 | INFO  | LogsAttachListener             | Packed logs in 500ms to C:\Users\REMOVED\AppData\Local\Temp\2\rider-logs-attachment.tar.xz
2020-04-09 10:45:33,109 | INFO  | ComponentStoreImpl             | Saving appFileTypeManager took 16 ms, IgnoreSettings took 15 ms, VSTSSettings took 16 ms
```

There are a lot of kerberos errosr which might be related to the issue. But I still don't understand why it works in TFS and not here or even why I can still get the list of my projects, which means that I must be authenticated correctly. It looks like the URL is the right one so that's that... Hopefully you can make sense of this. I'm at a loss here.

**Comment by ForNeVeR** [comment]
@kawazoe okay, could you try the same command in the command line?
```console
$ tf workspace -noprompt -collection:https://REMOVED/tfs/PROJECT -new -location:local rider "-comment:Workspace created through IntelliJ"
```

It should ask you for login/password afterwards.

My current hypothesis is that we somehow use right credentials ourselves when accessing the server, but pass the wrong ones to the command line.

Also, (I'm sorry, this is a very sensitive and security-related question, but it may be the case here) is it possible that your password contain any unusual characters such as `"`, `\`, `^`? In this case, we're passing the arguments via the command-line, and it may mangle some of them (I've not seen this before, but this is still a valid hypothesis).

**Comment by kawazoe** [comment]
Sooo... ehmmm.... it just started working today. I am not sure why.

I was trying to run the command line by hand. I was using the standalone java install that comes with rider to run it. It always completed without any output, so I tried to diagnose things a little. I added a `echo Return value: %RETURN_VALUE%` to the `:end` block just to see what was going on. It turns out the command was always returning a code 100, even when running `tf view`.

I already had a workspace created from VS, so I just tried to load the solution in Rider and import the source control config. It try to create a workspace with the name "Return value: 0", because of the echo statement I added, which failed because of invalid characters.

Still, that was a 0, so that meant the command succeed?! I removed the echo statement and unlinked the source control in Rider's settings thinking this shouldn't have worked.

When I tried to create a workspace again, it just worked...

My computer did reboot during the weekend, if that explains anything. Also, I am using a `^` in my password, but I never had to type it since it started working. I don't think my changes had anything to do with it. I didn't tried again this morning before running the command. Either something must have changed on the server since then to make it work, or the reboot did the trick.

I'm going to close this issue for now as I no longer have a way to reproduce it... Though I still don't know why it started working.

**Comment by ForNeVeR** [comment]
@kawazoe, thanks for the heads up. I'll still investigate the situation around `^` in the password. It is _too_ suspicious to not take a note. Feel free to reopen the issue if it reappears (which is very much possible). I'll try to mess around with my password to reproduce the issue.

Also, I have a possible explanation of why it randomly works sometimes and sometimes it doesn't, but it's probably crazy, so I'll have to reproduce it myself first.

**Comment by kawazoe** [comment]
Here's something interesting that I noticed. There is now two entries in "Azure DevOps Services / TFS" > "Configuration Management". One for "https://server/tfs" and one for "https://server/tfs/project". Both have the same user name. Maybe that explains why it started to work.

**Comment by ForNeVeR** [comment]
Alright, I was able to reproduce the issue.

**Prerequisites:** 
1. Use on-premise Azure DevOps server (dev.azure.com won't work because it uses other authentication token format; "alternate password" mechanism _could_ work but it is getting obsoleted anyway).
2. Azure DevOps Server user should have unusual character in their password (e.g. `^`).

**Steps to reproduce:**
1. Check out a repository from the IDE welcome screen: authenticate on server using your login/password
2. The authentication will work (!), the repository list will be loaded. Select a repository and path to check it out, press **Checkout**

The error will be shown:
```
java.lang.RuntimeException: An error occurred: Access denied connecting to TFS server http://desktop-i35dvo5/ (authenticating as friedrich)

	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:423)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.throwIfError(CreateWorkspaceCommand.java:91)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:73)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:22)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)
```

**Investigation:** the problem is that _under some circumstances_ we pass the login/password pair through `cmd` on Windows, and `cmd` is known for its really crazy rules of argument passing. Namely, `^` character is escape character in some contexts.

**Workaround:** the workaround here would be to switch the command-line client code to the so-called "fast-mode" (which isn't so fast, but still). I'll copy the information from my previous take on the issue, https://github.com/microsoft/azure-devops-intellij/issues/252#issuecomment-544838137:

> So, we have two ways of running the TF client: the "fast one" and the "slow one".
> 
> In the slow mode, we're passing all the arguments through the client command line (and it breaks for some reason on your machine: probably the credentials themselves are too long which happen sometimes).
> 
> In the fast mode, we start the client "worker" process with the only argument `@` which means "read the command line from stdin", and then pass the arguments through stdin, which is probably more reliable.
> 
> 
> For now, your workaround would be to do one of this:
> 1) open your TFVC settings and press the **Test** button on the client setup page: it should load the client version and will allow it to use the "fast mode" that isn't so bugged
> 2) always check out the repositories from the already started IDE (e.g. open another TFVC project before checking out a new one): when opening any TFVC project, we cache the client version, too, and will use the "fast mode" for further actions, even for checking out a new project

I have verified that this workaround works in my case (with unusual character in password).

**Comment by eldamir** [comment]
I have the same error as originally posted at the top here. My password is alphanumeric. No fancy characters. I've tried all the above suggestions, starting with importing the certs as suggested...

Our TFS is hosted internally and SSL cert is self-signed, it seems. So therefor, I naturally imported them all as suggested, but still get the `PKIX path building failed` error.

I get to sign in and it lists my projects, but when I select the project an try to checkout, I see the error.

The only non-ordinary thing I can find in my setup is that the repo name has a space in it, which gets encoded to `%20`, e.g. "https://tfs.ourdomain.com/tfs/MyGroup/Bla%20bla". Could that be an issue?

Is there any information I can provide to help you help me? What logs do you need? Where do I find them? I running Rider installed from Toolbox on Windows.

Thanks

**Comment by eldamir** [comment]
@ForNeVeR , any idea as to what the problem above may be about?
