### ISSUE TITLE
Very slow VCS refresh and Merge Conflicts

### ISSUE THREAD

**Issue by mboyko1979** [microsoft/azure-devops-intellij#342]
I've installed IDEA 2020.1.1 which has disabled (due to end of support) TFS plugin. So I was needed to switch to Azure-Devops plugin.

After tuning and converting my workspaces to Local I was able to start use the new plugin.
But... But VCS history refresh is so slow....
Also when I've updated workspace and got several conflicts my work was blocked for 20-30 mins. 
Because before merging of each file plugin spent several minutes(!) in fetching the contents

As I see in idea.logs command   "tf.cmd history"  was called too many times with the same arguments. Interesting that last argument in this command is not a workspace root folder. 

I have attached screenshot but  had to erased real names and pathes (working under NDA)
![idea log](https://user-images.githubusercontent.com/11078089/81000581-29055f80-8e4f-11ea-889a-362cee293d19.png)
!

Thanks

**Comment by ForNeVeR** [comment]
Hello! This is supposedly fixed by #320 (but the release isn't published yet). Though I can't remember anything about `tf history` being called too often; in my case, it was `tf info` which was improved in the reactive client.

Could you try the preview plugin build from `master`? Our CI server still have a little crysis, but some of the builds are available. Please download the artifact named `com.microsoft.vso.idea-1.160.0` from [this page](https://dev.azure.com/Microsoft-Git-Tools/Vsts-IntelliJ/_build/results?buildId=1200&view=artifacts&type=publishedArtifacts):
![image](https://user-images.githubusercontent.com/92793/81038982-f3558a80-8ed1-11ea-90fa-db74804ab114.png)

After you have downloaded the file, then install it into IDEA as a "plugin from disk":
![image](https://user-images.githubusercontent.com/92793/81039061-30ba1800-8ed2-11ea-950e-53213c8d2b28.png)

And don't forget to enable the experimental reactive client in the plugin settings:
![image](https://user-images.githubusercontent.com/92793/81039157-66f79780-8ed2-11ea-89f9-968830d43e38.png)

**Comment by ForNeVeR** [comment]
_Update:_ downloading unpacked artifacts isn't available for external users, so you'll have to download `artifact.20200501.2.6d49648f-6df6-5d41-afe6-bfaee354f834`, extract `com.microsoft.vso.idea-1.160.0.zip` from it, and then install `com.microsoft.vso.idea-1.160.0.zip` from IDEA.

**Comment by mboyko1979** [comment]
@ForNeVeR, thank you for your help. I've installed pointed plugin version.
idea.log looks much better - for now I don't see any repeatable TF requests.

Only thing (WARN) I see in the log is:

2020-05-05 20:16:39,497 [ 436328]   WARN - n.process.BaseOSProcessHandler - Process hasn't generated any output for a long time.
If it's a long-running mostly idle daemon process, consider overriding OSProcessHandler#readerOptions with 'BaseOutputReader.Options.forMostlySilentProcess()' to reduce CPU usage.
Command line: C:\Users\mboyko\AppData\Roaming\JetBrains\IntelliJIdea2020.1\plugins\com.microsoft.vso.idea\backend\bin\backend.bat 63574 C:\Users\mboyko\AppData\Local\JetBrains\IntelliJIdea2020.1\log\ReactiveTfsClient INFO 
java.lang.Throwable: Process creation:
	at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:31)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:46)
	at com.microsoft.alm.plugin.external.reactive.ReactiveTfvcClientHost.create(ReactiveTfvcClientHost.java:79)
	at com.microsoft.alm.plugin.external.reactive.ReactiveTfvcClientHolder.createNewClientAsync(ReactiveTfvcClientHolder.java:100)
	at com.microsoft.alm.plugin.external.reactive.ReactiveTfvcClientHolder.getClient(ReactiveTfvcClientHolder.java:58)
	at com.microsoft.alm.plugin.idea.tfvc.core.ReactiveTfvcClient.lambda$getStatusForFilesAsync$3(ReactiveTfvcClient.java:67)
	at com.microsoft.alm.plugin.idea.tfvc.core.ReactiveTfvcClient.traceTime(ReactiveTfvcClient.java:50)
	at com.microsoft.alm.plugin.idea.tfvc.core.ReactiveTfvcClient.getStatusForFilesAsync(ReactiveTfvcClient.java:63)
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcClient.getStatusForFiles(TfvcClient.java:52)
	at com.microsoft.alm.plugin.idea.tfvc.core.TFSChangeProvider.getChanges(TFSChangeProvider.java:103)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.actualUpdate(ChangeListManagerImpl.java:660)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.iterateScopes(ChangeListManagerImpl.java:573)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.lambda$updateImmediately$13(ChangeListManagerImpl.java:485)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.updateImmediately(ChangeListManagerImpl.java:445)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.lambda$new$0(ChangeListManagerImpl.java:125)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue$MyRunnable.run(UpdateRequestsQueue.java:216)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ForNeVeR** [comment]
@mboyko1979, the main question is: was your performance problem solved by this build?

Regarding the warning in the logs: it doesn't matter. We really should use the API for "mostly silent" processes, but we cannot since we target a wide range of IDEs, and the API isn't available everywhere.

We'll address this eventually, but for now it's not an issue.

**Comment by mboyko1979** [comment]
Performance is better at first sight.
I will test few days and report result. Thanks

**Comment by mboyko1979** [comment]
Hello @ForNeVeR ,

Looks like initial issue is resolved. I didn't observe recursive TF-calls anymore.  
What is still working slow - when I do Project Update and there are file conflicts.
You need to wait while list of conflicts is loading, and then if you select Merge certain conflict - you also need to wait some time.
Also if all conflicts are merged automatically - then empty "Merge Conflicts" window appears (unlike for other VCS).

Maybe new issues for this test cases should be created.

Thanks,
Max
