### ISSUE TITLE
Server workspace cannot be determined in project that includes modules outside the workspace as well

### ISSUE THREAD

**Issue by ronvanpol** [microsoft/azure-devops-intellij#367]
I've been testing the latest IntelliJ IDEA EAP. This includes a build that includes the support for server workspaces (see pull request #360). My project contains a combination of modules that are under control of Devops TFVC as well as Git. The Devops plugin is called for numerous different reasons and often it is called from a working directory outside the server workspace when the working directory points to on of my Git modules. As a result the workspace cannot be determined (KEY_TF_WORKSPACE_COULD_NOT_BE_DETERMINED) and the plugin fails miserably. 

```
2020-06-25 21:36:02,713 [ 228538]   INFO - alm.plugin.external.ToolRunner - ToolRunner.start: toolLocation = E:\TEE-CLC-14.134.0\tf.cmd 
2020-06-25 21:36:02,713 [ 228538]   INFO - alm.plugin.external.ToolRunner - ToolRunner.start: workingDirectory = E:\Github\Github\azure-devops-intellij\plugin\src\com\microsoft\alm\plugin\idea\git 
2020-06-25 21:36:02,713 [ 228538]   INFO - alm.plugin.external.ToolRunner - arguments: workfold -noprompt -login:username,pw 
2020-06-25 21:36:03,827 [ 229652]   INFO - ugin.external.commands.Command - ERROR: An argument error occurred: The workspace could not be determined from any argument paths or the current working directory. 

...

com.microsoft.alm.plugin.external.exceptions.WorkspaceCouldNotBeDeterminedException: KEY_TF_WORKSPACE_COULD_NOT_BE_DETERMINED
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.checkErrors(FindWorkspaceCommand.java:122)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:140)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:29)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:298)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:336)
```

**Comment by ForNeVeR** [comment]
Could you please clarify: you're using a version of plugin you've build from sources, right?

**Comment by ronvanpol** [comment]
I have used the version of the plugin that was distributed with the latest IntellJ IDEA EAP as well as a built from the latest sources here on github. Both showing the same result.

**Comment by ForNeVeR** [comment]
IDEA doesn't embed the Azure DevOps plugin (and never did). I believe you're confused about how the plugins work across EAPs: probably you had just installed it in earlier version, and then reused the same profile with EAP build of IDEA (and thus got the plugin installed there).

Thanks for menitioneing the issue though: we've never tested the plugin on multi-module projects where not every module is included under version control. I'll take a look.

**Comment by ronvanpol** [comment]
I think you're right about the automatic installation of the DevOps plugin. My apologies for the confusion. I'm glad to hear that you will be investigation the multi-module issue though. Looking forward to a fix. Thanks in advance.

**Comment by ronvanpol** [comment]
Any news on this issue? IntelliJ IDEA 2020.2 RC has already been released. I would hate to have a wait another 3 months to get things working.

**Comment by ForNeVeR** [comment]
As a side note, release cycle of this plugin doesn't rely on IDEA at all: the plugin and IDEA are released completely independently of each other.

Unfortunately, we wasn't able to begin this particular investigation yet, but it isn't forgotten and is in our task queue.

**Comment by ForNeVeR** [comment]
I was able to reproduce the issue. It seems like we really lack the multi-module support (we rely on single VCS root being created for the whole project in multiple places). I've created a more focused issue about multi-root support: #376.

I'll close this one as a duplicate.
