### ISSUE TITLE
Cannot create a TFVC workspace

### ISSUE THREAD

**Issue by juliusbartolome** [microsoft/azure-devops-intellij#389]
Hello there! I am new to the extension and try to use it to pull files from on-site Azure DevOps 2017 TFVC project files using Jetbrains Rider 2020.2.1. I am using windows 10 with both Visual 2019 Enterprise (preview - 16.8.0 and release 16.7.2) installed. 

For the TFVC settings (Settings > Version Control > TFVC) - I have the following values set:
```
Classic TF command-line client: C:\Users\jpjb\TEE-CLC-14.134.0\tf.cmd
Use built-in reactive client if possible (faster, experimental): unchecked
Visual Studio TF Client (important only): C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe
```

Steps to recreate:
1. Open Rider from Task bar.
2. Click "Get from Version Control"
3. From "Version Control" dropdown, select "Azure DevOps TFVC"
4. Click "Clone"
5. Input Server URL then press "Connect"
6. Enter credentials
7. Select Repository item from the list
8. Checked - Edit the workspace before getting sources
9. Added "Directory Name" value
10. Clicked "Create Workspace"
11. A pop-up opens with a progress bar but after a second or two it disappears and displays the IDE Fatal Errors window.

This is the `stacktrace.txt` content from the IDE Fatal Errors window:
```
java.lang.RuntimeException: An argument error occurred: The workspace could not be determined from any argument paths or the current working directory.
'-+' is not recognized as an internal or external command,
operable program or batch file.

	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:438)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.throwIfError(CreateWorkspaceCommand.java:114)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:96)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:22)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)
```
 
I hope this could be fixed.

Thanks,
Julius

**Comment by juliusbartolome** [comment]
Sorry my fault, the issue was because I didn't setup the `JAVA_HOME` environment and added the `bin` to `PATH`. Thanks! It works now!
