### ISSUE TITLE
Failed to get changes from command line. roots=D:/PATH/project/xyz

### ISSUE THREAD

**Issue by khamza85** [microsoft/azure-devops-intellij#393]
Failed to get changes from command line. roots=D:/...

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Lifetime in 'Terminated', can't add termination actions
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcClient.getStatusForFiles(TfvcClient.java:57)
	at com.microsoft.alm.plugin.idea.tfvc.core.TFSChangeProvider.getChanges(TFSChangeProvider.java:103)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.actualUpdate(ChangeListManagerImpl.java:669)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.iterateScopes(ChangeListManagerImpl.java:587)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.lambda$updateImmediately$10(ChangeListManagerImpl.java:492)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.lambda$updateImmediately$13(ChangeListManagerImpl.java:491)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$11(BackgroundTaskUtil.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:251)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:227)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.updateImmediately(ChangeListManagerImpl.java:446)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue$MyRunnable.run(UpdateRequestsQueue.java:219)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:215)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:194)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:183)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Lifetime in 'Terminated', can't add termination actions
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcClient.getStatusForFiles(TfvcClient.java:55)
	... 33 more
Caused by: java.lang.IllegalStateException: Lifetime in 'Terminated', can't add termination actions
	at com.jetbrains.rd.util.lifetime.RLifetimeKt.badStatusForAddActions(RLifetime.kt:344)
	at com.jetbrains.rd.util.lifetime.RLifetimeKt.onTermination(RLifetime.kt:349)
	at com.microsoft.tfs.connector.ReactiveClientConnection.queueFutureAsync(ReactiveClientConnection.kt:124)
	at com.microsoft.tfs.connector.ReactiveClientConnection.getOrCreateCollectionAsync(ReactiveClientConnection.kt:51)
	at com.microsoft.alm.plugin.external.reactive.ReactiveTfvcClientHost.getReadyCollectionAsync(ReactiveTfvcClientHost.java:280)
	at com.microsoft.alm.plugin.external.reactive.ReactiveTfvcClientHost.getPendingChangesAsync(ReactiveTfvcClientHost.java:147)
	at com.microsoft.alm.plugin.idea.tfvc.core.ReactiveTfvcClient.lambda$null$2(ReactiveTfvcClient.java:71)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at com.microsoft.alm.plugin.idea.tfvc.core.ReactiveTfvcClient.lambda$getStatusForFilesAsync$3(ReactiveTfvcClient.java:71)
	at com.microsoft.alm.plugin.idea.tfvc.core.ReactiveTfvcClient.traceTime(ReactiveTfvcClient.java:53)
	at com.microsoft.alm.plugin.idea.tfvc.core.ReactiveTfvcClient.getStatusForFilesAsync(ReactiveTfvcClient.java:66)
	... 34 more
```

**Comment by ForNeVeR** [comment]
Hi! This doesn't look good, could you please share `idea.log` and `ReactiveTfsClient` subdirectory from the log directory? **Help → Diagnostic Tools → Show Log in Explorer** should help you to get them.

For now, the workaround could be to disable the reactive client in the TFVC Version Control settings. Try it, please.

**Comment by khamza85** [comment]
[ReactiveTfsClient.zip](https://github.com/microsoft/azure-devops-intellij/files/5178347/ReactiveTfsClient.zip)

[idea.log.1.zip](https://github.com/microsoft/azure-devops-intellij/files/5178352/idea.log.1.zip)

**Comment by ForNeVeR** [comment]
For now, it is completely unclear what's happening there. I'll try to improve the client lifetime logging.

**Comment by ateber91** [comment]
The same issue here!

**Comment by zelteh** [comment]
Hi, same issue here

Version 1.162.0

Failed to get changes from command line. roots=D:/Projects/MojOtpad

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcClient.getStatusForFiles(TfvcClient.java:60)
	at com.microsoft.alm.plugin.idea.tfvc.core.TFSChangeProvider.getChanges(TFSChangeProvider.java:103)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.actualUpdate(ChangeListManagerImpl.java:696)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.iterateScopes(ChangeListManagerImpl.java:596)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.lambda$updateImmediately$11(ChangeListManagerImpl.java:502)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.lambda$updateImmediately$14(ChangeListManagerImpl.java:501)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$12(BackgroundTaskUtil.java:336)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:335)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:327)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.updateImmediately(ChangeListManagerImpl.java:455)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue$MyRunnable.run(UpdateRequestsQueue.java:212)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl$MyLoggingRunnable.run(ChangeListManagerImpl.java:1699)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:223)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcClient.getStatusForFiles(TfvcClient.java:58)
	... 39 more
Caused by: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2396)
	at com.microsoft.tfs.connector.ReactiveClientConnection$queueFutureAsync$1.invoke(ReactiveClientConnection.kt:138)
	at com.microsoft.tfs.connector.ReactiveClientConnection$queueFutureAsync$1.invoke(ReactiveClientConnection.kt:18)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.destruct(RLifetime.kt:266)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.terminate(RLifetime.kt:252)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.destruct(RLifetime.kt:272)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.terminate(RLifetime.kt:252)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.terminate$default(RLifetime.kt:226)
	at com.microsoft.tfs.connector.ReactiveClientConnection$$special$$inlined$apply$lambda$1.invoke(ReactiveClientConnection.kt:25)
	at com.microsoft.tfs.connector.ReactiveClientConnection$$special$$inlined$apply$lambda$1.invoke(ReactiveClientConnection.kt:18)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:29)
	at com.jetbrains.rd.util.reactive.Property.setValue(Property.kt:13)
	at com.jetbrains.rd.framework.SocketWire$Base$1$3.invoke(SocketWire.kt:104)
	at com.jetbrains.rd.framework.SocketWire$Base$1$3.invoke(SocketWire.kt:65)
	at com.jetbrains.rd.util.threading.SingleThreadSchedulerBase$queue$1.run(SingleThreadScheduler.kt:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more


AND 

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Lifetime in 'Terminated', can't add termination actions
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcClient.getBasicWorkspaceInfo(TfvcClient.java:328)
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcWorkspaceLocator.getPartialWorkspace(TfvcWorkspaceLocator.java:45)
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcWorkspaceLocator.getPartialWorkspace(TfvcWorkspaceLocator.java:90)
	at com.microsoft.alm.plugin.idea.tfvc.core.tfs.TFVCUtil.getMappingsFromWorkspace(TFVCUtil.java:111)
	at com.microsoft.alm.plugin.idea.tfvc.core.tfs.TFVCUtil.filterValidTFVCPaths(TFVCUtil.java:78)
	at com.microsoft.alm.plugin.idea.tfvc.core.TFSChangeProvider.getChanges(TFSChangeProvider.java:95)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.actualUpdate(ChangeListManagerImpl.java:696)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.iterateScopes(ChangeListManagerImpl.java:596)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.lambda$updateImmediately$11(ChangeListManagerImpl.java:502)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.lambda$updateImmediately$14(ChangeListManagerImpl.java:501)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$12(BackgroundTaskUtil.java:336)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:335)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:327)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.updateImmediately(ChangeListManagerImpl.java:455)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue$MyRunnable.run(UpdateRequestsQueue.java:212)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl$MyLoggingRunnable.run(ChangeListManagerImpl.java:1699)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:223)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Lifetime in 'Terminated', can't add termination actions
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcClient.getBasicWorkspaceInfo(TfvcClient.java:326)
	... 43 more
Caused by: java.lang.IllegalStateException: Lifetime in 'Terminated', can't add termination actions
	at com.jetbrains.rd.util.lifetime.RLifetimeKt.badStatusForAddActions(RLifetime.kt:344)
	at com.jetbrains.rd.util.lifetime.RLifetimeKt.onTermination(RLifetime.kt:349)
	at com.microsoft.tfs.connector.ReactiveClientConnection.queueFutureAsync(ReactiveClientConnection.kt:138)
	at com.microsoft.tfs.connector.ReactiveClientConnection.getBasicWorkspaceInfoAsync(ReactiveClientConnection.kt:122)
	at com.microsoft.alm.plugin.external.reactive.ReactiveTfvcClientHost.getBasicWorkspaceInfoAsync(ReactiveTfvcClientHost.java:273)
	at com.microsoft.alm.plugin.idea.tfvc.core.ReactiveTfvcClient.lambda$null$24(ReactiveTfvcClient.java:204)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at com.microsoft.alm.plugin.idea.tfvc.core.ReactiveTfvcClient.lambda$getBasicWorkspaceInfoAsync$25(ReactiveTfvcClient.java:204)
	at com.microsoft.alm.plugin.idea.tfvc.core.ReactiveTfvcClient.traceTime(ReactiveTfvcClient.java:55)
	at com.microsoft.alm.plugin.idea.tfvc.core.ReactiveTfvcClient.getBasicWorkspaceInfoAsync(ReactiveTfvcClient.java:203)
	... 44 more
