### ISSUE TITLE
ERROR | PluginManager | Task com.microsoft.alm.plugin.operations.OperationExecutor$1@179b2c47 rejected from java.util.concurrent.ThreadPoolExecutor@3ae57109[Running, pool size = 5, active threads = 5, queued tasks = 50, completed tasks = 280]

### ISSUE THREAD

**Issue by khamza85** [microsoft/azure-devops-intellij#395]
Basically starts happening for any TFVC upstream operation (refresh, update..) if I don't close Rider for a day or two.

```
java.util.concurrent.RejectedExecutionException: Task com.microsoft.alm.plugin.operations.OperationExecutor$1@179b2c47 rejected from java.util.concurrent.ThreadPoolExecutor@3ae57109[Running, pool size = 5, active threads = 5, queued tasks = 50, completed tasks = 280]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at com.microsoft.alm.plugin.operations.OperationExecutor.execute(OperationExecutor.java:52)
	at com.microsoft.alm.plugin.operations.OperationExecutor.executeAsync(OperationExecutor.java:43)
	at com.microsoft.alm.plugin.operations.Operation.doWorkAsync(Operation.java:113)
	at com.microsoft.alm.plugin.idea.common.statusBar.StatusBarManager.updateWidgets(StatusBarManager.java:112)
	at com.microsoft.alm.plugin.idea.common.statusBar.StatusBarManager.updateStatusBar(StatusBarManager.java:81)
	at com.microsoft.alm.plugin.idea.common.statusBar.BuildPopup$2.actionPerformed(BuildPopup.java:68)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:980)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1024)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6650)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6415)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5025)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:967)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:904)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:503)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2020-09-10 00:18:46,109 | ERROR | PluginManager                  | JetBrains Rider 2020.2.1  Build #RD-202.6397.268
2020-09-10 00:18:46,109 | ERROR | PluginManager                  | JDK: 11.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2020-09-10 00:18:46,109 | ERROR | PluginManager                  | OS: Windows 10
2020-09-10 00:18:46,109 | ERROR | PluginManager                  | Plugin to blame: Azure DevOps version: 1.161.0
```

Plugin version: 1.161.0
TF client: TEE-CLC-14.135.1 (jetbrains's fork)
Server: Azure Repos
OS: Windows 10
IDE: Rider 2020.2.1

**Comment by ForNeVeR** [comment]
Could you please share the IDE logs gathered after this issue happens?

**Comment by khamza85** [comment]
Sure, full log.
[idea - Copy.zip](https://github.com/microsoft/azure-devops-intellij/files/5199786/idea.-.Copy.zip)
