### ISSUE TITLE
KEY_TF_WORKSPACE_COULD_NOT_BE_DETERMINED

### ISSUE THREAD

**Issue by hoppermandr** [microsoft/azure-devops-intellij#399]
I am getting this error with the Azure Devops Plugin v. 1.161.0 in IntelliJ IDEA 2020.2

com.microsoft.alm.plugin.external.exceptions.WorkspaceCouldNotBeDeterminedException: KEY_TF_WORKSPACE_COULD_NOT_BE_DETERMINED
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.checkErrors(FindWorkspaceCommand.java:121)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:139)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:29)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)

At first I thought it might be authorization related, but frankly I'm not sure it is anymore.  I did verify that the credentials I enter via the Web UI, and the Visual Studio IDE Team Explorer pane, are the same as what's in IntelliJ.

**Comment by ForNeVeR** [comment]
Hello. Could you please explain what actions lead to this error?

**Comment by hoppermandr** [comment]
This is for the general integration, so integration is not working at all at the moment.  I have the plugin installed and configured (to what I think is correct), but Intellij is unable to display information about the repository, or perform any of the operations (check out, get, compare, commit, etc).

Today I can get this message upon launch, going into the VersionControl tab, and clicking on "refresh".

I just checked, and here's a related (auth) error that wasn't there yesterday when I captured the stack trace above.

javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
	at com.microsoft.alm.plugin.idea.tfvc.core.TFSVcs.getServerContext(TFSVcs.java:289)
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcEditFileProvider.editFiles(TfvcEditFileProvider.java:32)
	at com.intellij.openapi.vcs.readOnlyHandler.VcsHandleType.processFiles(VcsHandleType.java:46)
        . . . .

**Comment by ForNeVeR** [comment]
Could you please post the steps that leads to these errors, from the beginning (i.e. the repository setup)? Thanks.

For example, you're saying:
> I did verify that the credentials I enter via the Web UI, and the Visual Studio IDE Team Explorer pane, are the same as what's in IntelliJ.

Where and at which moment do you enter these credentials into IntelliJ?

**Comment by hoppermandr** [comment]
I installed the Azure DevOps Services / TFS plugin so it shows up on Intellij Settings | Version Control.
In Settings | Version Control | Azure DevOps Services / TFS, I select the appropriate repository (only one is shown) on the table, and click on the "Update Credentials" button.  On the dialog box that pops up, I enter my Login and Password.  I enter these values exactly as I enter them in the Azure DevOps web UI, which works.

I click on Settings | Version Control, select the directory where my project files are in, and under the VCS column, I click on the dropdown and select "TFVC"

**Comment by ForNeVeR** [comment]
Usually, `KEY_TF_WORKSPACE_COULD_NOT_BE_DETERMINED` is thrown if the TFVC client is unable to tell us about the workspace when we ask it about it.

Could you try to open the project directory and invoke the TFVC client command `tf.cmd -login user,user workfold`?

**Comment by hoppermandr** [comment]
The command worked fine, and listed items that I expected to see. 
![image](https://user-images.githubusercontent.com/26576243/94608846-9df48e00-0263-11eb-8a06-f46eef4f8282.png)

**Comment by hoppermandr** [comment]
The tf.cmd referenced is the one configured in Intellij.

![image](https://user-images.githubusercontent.com/26576243/94609114-fd529e00-0263-11eb-8497-a694c57d577f.png)

**Comment by ForNeVeR** [comment]
Alright, could you please share the IDE log then? It should tell us what's wrong; probably it was calling the command from the wrong directory or something like that.

**Comment by hoppermandr** [comment]
Here's what I'm seeing repeat over and over.  

[idea.ms.log](https://github.com/microsoft/azure-devops-intellij/files/5308447/idea.ms.log)

**Comment by hoppermandr** [comment]
> It should tell us what's wrong; probably it was calling the command from the wrong directory or something like that.

Yes, this looks to be the problem.  My directory is set up this way:

```
+ Workspace
|--+ ProjectA
    |--+ projectfiles
    |--+ actualcode
|--+ ProjectB
    |--+ projectfiles
    |--+ actualcode
```
"projectfiles" is a local directory I set up where IDE files, local build output, temp libraries, etc, and other stuff that shouldn't be in the source repo are placed.  This includes the .idea directory and module files, things like that.  This directory is local only, is not mapped to the TFS, er, AzureDevOps source repo at all.

"actualcode" is the directory that is mapped to the ADO workspace and is where the real stuff is in.  When I run the 'workfold' command, this directory is included in the list.

**Comment by ForNeVeR** [comment]
Alright, now I understand the issue.

Unfortunately, currently we don't support this kind of workspaces. Your VCS root **have** to be the same as the project root. There's the main issue I've reported: #376.

This one is a duplicate, then.

A workaround would be to move the project files so they correspond to the VCS root.
