### ISSUE TITLE
The plugin is unable to find the TFS server workspace.

### ISSUE THREAD

**Issue by mandojim** [microsoft/azure-devops-intellij#402]
Here is the error thrown by RubyMine:
java.lang.NullPointerException
	at com.microsoft.alm.plugin.external.utils.CommandUtils.getPartialWorkspace(CommandUtils.java:137)
	at com.microsoft.alm.plugin.idea.tfvc.extensions.TfvcRootChecker.lambda$isRoot$1(TfvcRootChecker.java:73)
	at com.microsoft.alm.plugin.idea.tfvc.ui.settings.EULADialog.executeWithGuard(EULADialog.java:226)
	at com.microsoft.alm.plugin.idea.tfvc.extensions.TfvcRootChecker.isRoot(TfvcRootChecker.java:69)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.lambda$getVcsRootFor$4(VcsRootDetectorImpl.java:175)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:55)
	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.java:57)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.getVcsRootFor(VcsRootDetectorImpl.java:174)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.getVcsRootFor(VcsRootDetectorImpl.java:167)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.lambda$scanForRootsInsideDir$3(VcsRootDetectorImpl.java:115)
	at com.intellij.openapi.vcs.roots.VcsRootScanner$1.visitFileEx(VcsRootScanner.java:105)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:292)
	at com.intellij.openapi.vcs.roots.VcsRootScanner.visitDirsRecursivelyWithoutExcluded(VcsRootScanner.java:89)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.scanForRootsInsideDir(VcsRootDetectorImpl.java:110)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.scanForRootsInContentRoots(VcsRootDetectorImpl.java:99)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.detect(VcsRootDetectorImpl.java:43)
	at com.intellij.openapi.vcs.roots.VcsRootErrorsFinder.find(VcsRootErrorsFinder.java:34)
	at com.intellij.openapi.vcs.roots.VcsRootProblemNotifier.scan(VcsRootProblemNotifier.java:191)
	at com.intellij.openapi.vcs.roots.VcsRootProblemNotifier.rescanAndNotifyIfNeeded(VcsRootProblemNotifier.java:74)
	at com.intellij.openapi.vcs.roots.VcsRootScanner.lambda$scheduleScan$4(VcsRootScanner.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254)
	at com.intellij.openapi.vcs.roots.VcsRootScanner.lambda$scheduleScan$5(VcsRootScanner.java:119)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
	at com.intellij.util.Alarm$Request.run(Alarm.java:356)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:215)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:194)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:183)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ForNeVeR** [comment]
@mandojim, could you please attach the IDE logs? Logs from a couple of seconds near this exception should usually be enough. Thanks in advance!

**Comment by ForNeVeR** [comment]
Unfortunately, without the requested follow-up information, this issue is completely unactionable. Feel free to reopen if you'll be able to collect the information. Thanks!
