### ISSUE TITLE
Fatal error when create workspace fromd devops

### ISSUE THREAD

**Issue by ahmettsoner** [microsoft/azure-devops-intellij#406]
After select project and click "Create Workspace" button i got an error in "IDE Fatal Errors" window

java.lang.RuntimeException: The syntax of the command is incorrect.

	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:438)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.throwIfError(CreateWorkspaceCommand.java:114)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:96)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:22)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)
![Screenshot_101](https://user-images.githubusercontent.com/6427713/98084656-31d1ff00-1e8d-11eb-9c22-ccbe82ca6b6c.png)
![Screenshot_102](https://user-images.githubusercontent.com/6427713/98084658-33032c00-1e8d-11eb-94a4-fef62cff2213.png)

**Comment by ForNeVeR** [comment]
Could you please attach the relevant IDE logs?

**Comment by ahmettsoner** [comment]
Thanks for reply @ForNeVeR , here that my log records



2020-11-04 14:08:02,601 [11637133]   INFO - n.context.ServerContextManager - AuthenticatedInfo found for url https://app.vssps.visualstudio.com 
2020-11-04 14:08:02,601 [11637133]   INFO - .checkout.VsoCheckoutPageModel - Loading contexts in constructor 
2020-11-04 14:08:02,601 [11637133]   INFO - n.context.ServerContextManager - AuthenticatedInfo found for url https://app.vssps.visualstudio.com 
2020-11-04 14:08:02,601 [11637133]   INFO - n.context.ServerContextManager - AuthenticatedInfo found for url https://app.vssps.visualstudio.com 
2020-11-04 14:08:02,602 [11637134]   INFO - n.context.ServerContextManager - AuthenticatedInfo found for url https://app.vssps.visualstudio.com 
2020-11-04 14:08:02,857 [11637389]   INFO - n.context.ServerContextManager - AuthenticatedInfo found for url https://app.vssps.visualstudio.com 
2020-11-04 14:08:02,858 [11637390]   INFO - on.ServerContextLookupListener - loadContexts activeOperation with 1 contexts and a scope of PROJECT 
2020-11-04 14:08:02,858 [11637390]   INFO - on.ServerContextLookupListener - loadContexts terminateActiveOperation in state NOT_STARTED 
2020-11-04 14:08:02,858 [11637390]   INFO - on.ServerContextLookupListener - ServerContext operation terminated 
2020-11-04 14:08:02,858 [11637390]   INFO - on.ServerContextLookupListener - ServerContext lookup started 
2020-11-04 14:08:02,858 [11637390]   INFO - .services.HttpProxyServiceImpl - useHttpProxy: false 
2020-11-04 14:08:04,190 [11638722]   INFO - on.ServerContextLookupListener - ServerContext lookup results has error: false 
2020-11-04 14:08:04,190 [11638722]   INFO - on.ServerContextLookupListener - ServerContext lookup completed 
2020-11-04 14:08:04,190 [11638722]   INFO - on.ServerContextLookupListener - ServerContext operation done 
2020-11-04 14:08:08,198 [11642730]   INFO - .services.HttpProxyServiceImpl - useHttpProxy: false 
2020-11-04 14:08:08,685 [11643217]   INFO - .auth.pat.VstsPatAuthenticator - Retrieving PersonalAccessToken for uri:https://dev.azure.com/OrganizationName with name:Azure DevOps IntelliJ Plugin: user@OrganizationName.com from: DESKTOP-A334ICB on: Wed Nov 04 14:08:08 TRT 2020, and with scope:, prompt behavior: AUTO 
2020-11-04 14:08:08,960 [11643492]   INFO - lugin.external.ToolRunnerCache - getRunningToolRunner: toolLocation=F:\C\F\Downloads\TEE-CLC-14.135.0\TEE-CLC-14.135.0\tf.cmd 
2020-11-04 14:08:08,960 [11643492]   INFO - lugin.external.ToolRunnerCache - getRunningToolRunner: slow version - null 
2020-11-04 14:08:08,960 [11643492]   INFO - alm.plugin.external.ToolRunner - ToolRunner.start: toolLocation = F:\C\F\Downloads\TEE-CLC-14.135.0\TEE-CLC-14.135.0\tf.cmd 
2020-11-04 14:08:08,960 [11643492]   INFO - alm.plugin.external.ToolRunner - ToolRunner.start: workingDirectory = null 
2020-11-04 14:08:08,960 [11643492]   INFO - alm.plugin.external.ToolRunner - arguments: workspace -noprompt -collection:https://dev.azure.com/OrganizationName ******** -new -location:local Project Name -comment:Workspace created through IntelliJ 
2020-11-04 14:08:08,972 [11643504]   WARN - .AbstractProgressIndicatorBase - This progress indicator is indeterminate, this may lead to visual inconsistency. Please call setIndeterminate(false) before you start progress.
com.microsoft.alm.plugin.idea.common.utils.IdeaHelper$1.run(IdeaHelper.java:65) 
2020-11-04 14:08:09,019 [11643551]   INFO - ugin.external.commands.Command - ERROR: The syntax of the command is incorrect. 
2020-11-04 14:08:09,021 [11643553]   WARN - ugin.external.commands.Command - CMD: parsing output failed 
java.lang.RuntimeException: The syntax of the command is incorrect.

	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:438)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.throwIfError(CreateWorkspaceCommand.java:114)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:96)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:22)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)
2020-11-04 14:08:09,022 [11643554]   WARN - ugin.external.commands.Command - Error: java.lang.RuntimeException: The syntax of the command is incorrect.

Sync stack trace: java.base/java.lang.Thread.getStackTrace(Thread.java:1607)
    at com.microsoft.alm.plugin.external.commands.Command.runSynchronously(Command.java:243)
    at com.microsoft.alm.plugin.idea.tfvc.ui.settings.EULADialog.executeWithGuard(EULADialog.java:226)
    at com.microsoft.alm.plugin.idea.tfvc.ui.checkout.TfvcCheckoutModel$1.run(TfvcCheckoutModel.java:91)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.base/java.lang.Thread.run(Thread.java:834) 
2020-11-04 14:08:09,022 [11643554]   INFO - ugin.external.commands.Command - 0.061262 sec - elapsed time for workspace -noprompt -collection:https://dev.azure.com/OrganizationName ******** -new -location:local Project Name -comment:Workspace created through IntelliJ 
2020-11-04 14:08:09,022 [11643554]   INFO -                         STDERR - : 0.061262 sec - elapsed time for workspace -noprompt -collection:https://dev.azure.com/OrganizationName ******** -new -location:local Project Name -comment:Workspace created through IntelliJ 
2020-11-04 14:08:09,022 [11643554]  ERROR - intellij.openapi.progress.Task - The syntax of the command is incorrect.
 
java.lang.RuntimeException: The syntax of the command is incorrect.

	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:438)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.throwIfError(CreateWorkspaceCommand.java:114)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:96)
	at com.microsoft.alm.plugin.external.commands.CreateWorkspaceCommand.parseOutput(CreateWorkspaceCommand.java:22)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)
2020-11-04 14:08:09,022 [11643554]  ERROR - intellij.openapi.progress.Task - PhpStorm 2020.2.3  Build #PS-202.7660.42 
2020-11-04 14:08:09,022 [11643554]  ERROR - intellij.openapi.progress.Task - JDK: 11.0.8; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-11-04 14:08:09,022 [11643554]  ERROR - intellij.openapi.progress.Task - OS: Windows 10 
2020-11-04 14:08:09,022 [11643554]  ERROR - intellij.openapi.progress.Task - Plugin to blame: Azure DevOps version: 1.161.0 
2020-11-04 14:08:09,023 [11643555]  ERROR - intellij.openapi.progress.Task - Last Action: Vcs.VcsClone 
2020-11-04 14:08:11,146 [11645678]   INFO - rationStore.ComponentStoreImpl - Saving appEditorColorsManagerImpl took 12 ms

**Comment by ForNeVeR** [comment]
Alright. The suspicious part is `getRunningToolRunner: slow version`. This makes the issue similar to #323. Could you please try a workaround from https://github.com/microsoft/azure-devops-intellij/issues/323#issuecomment-613826895?

**Comment by ahmettsoner** [comment]
i tried your suggestion, changed my pasword like "1Tgdfgerw24" but couldn't configure workspace, got same error @ForNeVeR

**Comment by ForNeVeR** [comment]
Could you please attach more logs?

**Comment by ForNeVeR** [comment]
Also, please **don't share passwords** in a public issue tracker! Please change that one to something else.

**Comment by ahmettsoner** [comment]
Hi dear, i tried a lot of things in last a few day, changed my password, changed workspace names etc. But couln't get my files to locale. Then i changed my tf.cmd (TEE-CLC-14.0.3.zip) location to "C" drive then try again and boom it's worked :)

Thanks for your replies @ForNeVeR , i was just show how look like my pasword :) that was not real pass :)

**Comment by ForNeVeR** [comment]
@ahmettsoner, where was the client stored earlier? Could it be your user profile folder? Does your Windows user name contain any unusual (non-Latin) characters?

**Comment by ahmettsoner** [comment]
tf.cmd was in D: drive and moved to C: drive and worked. Windows username is not contain any non-latin chars

**Comment by ForNeVeR** [comment]
It is still unclear why was it broken, but, if it works now for you, then I'll close the issue.

I still suspect that the core reason was #323.

Thanks for report and for detailed information!
