### ISSUE TITLE
I am constantly required to sign in

### ISSUE THREAD

**Issue by tyrongower** [microsoft/azure-devops-intellij#408]
I have tried username and password and device flow, using credential helper and not. But i am constantly required to login again, and using MFA this means getting a text each time. 

This can happen when first open and when in the middle of working.  Not sure what the cause is, I was getting the same problem 6 months ago and stopped using it. 

Windows 10 Domain Joined
Domain Synced to Azure Ad
Rider 2020.2.4
Authentication using Work/School MS account

**Comment by ForNeVeR** [comment]
Could you share the IDE logs around the moment when this happens?

**Comment by tyrongower** [comment]
This is from this morning, after restarting Rider. I have sanitized names etc 

2020-11-12 08:21:07,808 | INFO  | PerformancePlugin              | Performance Plugin is in silent mode
2020-11-12 08:21:08,422 | INFO  | RiderDotNetActiveRuntimeHost   | Update active runtime: RdActiveRuntime(monoExePath=null, dotNetCliExePath=C:\Program Files\dotnet\dotnet.exe, dotNetCoreSdkList=[3.1.402, 3.1.403, 5.0.100-rc.2.20479.15])
2020-11-12 08:21:08,433 | INFO  | PencilsStatusBarWidget         | iconInEditor Editor
2020-11-12 08:21:08,434 | INFO  | PencilsInEditorIconController  | PencilsInEditorIconController start
2020-11-12 08:21:08,434 | INFO  | PencilsInEditorIconController  | targetScrollBar in: com.jetbrains.rd.util.reactive.Property@2d46bb1c
2020-11-12 08:21:08,435 | INFO  | PencilsInEditorIconController  | targetEditor in: com.jetbrains.rd.util.reactive.Property@5cea63f5
2020-11-12 08:21:08,436 | INFO  | PencilsInEditorIconController  | targetEditor out
2020-11-12 08:21:08,436 | INFO  | PencilsInEditorIconController  | targetEditor in: com.jetbrains.rd.util.reactive.Property@5cea63f5
2020-11-12 08:21:08,436 | INFO  | PencilsInEditorIconController  | targetScrollBar out
2020-11-12 08:21:08,436 | INFO  | PencilsInEditorIconController  | targetScrollBar in: com.jetbrains.rd.util.reactive.Property@2d46bb1c
2020-11-12 08:21:08,437 | INFO  | EditorPencilsIcon              | EditorPencilsIcon start
2020-11-12 08:21:08,536 | DEBUG | RiderFileBreadcrumbsCollector  | backend breadcrumbs support handles file = true
2020-11-12 08:21:08,543 | DEBUG | RiderFileBreadcrumbsCollector  | backend breadcrumbs support handles file = true
2020-11-12 08:21:08,544 | DEBUG | RiderFileBreadcrumbsCollector  | backend breadcrumbs support handles file = true
2020-11-12 08:21:08,545 | DEBUG | RiderFileBreadcrumbsCollector  | backend breadcrumbs support handles file = true
2020-11-12 08:21:08,545 | DEBUG | RiderFileBreadcrumbsCollector  | backend breadcrumbs support handles file = true
2020-11-12 08:21:08,546 | DEBUG | RiderFileBreadcrumbsCollector  | backend breadcrumbs support handles file = true
2020-11-12 08:21:08,547 | DEBUG | RiderFileBreadcrumbsCollector  | backend breadcrumbs support handles file = true
2020-11-12 08:21:08,548 | DEBUG | RiderFileBreadcrumbsCollector  | backend breadcrumbs support handles file = true
2020-11-12 08:21:08,554 | INFO  | CloudConfigManager             | === StatusBar.update another widget: null ===
2020-11-12 08:21:08,663 | INFO  | ExternalProjectsDataStorage    | Load external projects data in 3 millis (read time: 1)
2020-11-12 08:21:08,714 | INFO  | GitHandler                     | [.] git version
2020-11-12 08:21:08,776 | INFO  | GitHandler                     | git version 2.28.0.windows.1
2020-11-12 08:21:08,786 | INFO  | GitExecutableManager           | Git version for C:\Program Files\Git\cmd\git.exe: 2.28.0.0 (MSYS)
2020-11-12 08:21:08,952 | INFO  | CloudConfigManager             | === StatusBar.update another widget: null ===
2020-11-12 08:21:08,952 | DEBUG | RiderFileBreadcrumbsCollector  | backend breadcrumbs support handles file = true
2020-11-12 08:21:08,954 | DEBUG | RiderFileBreadcrumbsCollector  | start computing crumbs for the file file://D:/Projects/project-name/Core/Processes/AutoDocuments.cs and offset 2836
2020-11-12 08:21:08,984 | INFO  | ProjectRepoEventManager        | repository changed
2020-11-12 08:21:08,984 | INFO  | ServerEventManager             | triggering ALL events
2020-11-12 08:21:08,985 | INFO  | ServerEventManager             | triggering event: BUILDS_CHANGED
2020-11-12 08:21:08,985 | INFO  | ServerEventManager             | triggering event: PULL_REQUESTS_CHANGED
2020-11-12 08:21:08,986 | INFO  | ServerEventManager             | triggering event: WORK_ITEMS_CHANGED
2020-11-12 08:21:08,996 | INFO  | SolutionLifecycleHost          | Got SolutionBuilder is ready signal from backend
2020-11-12 08:21:09,227 | INFO  | ProjectConfig                  | Already migrated
2020-11-12 08:21:09,247 | WARN  | CachedStatusCalculator         | Hash mismatch between count and status: RevListCount[value=<null>,status=NO_REMOTE,top=<null>] ahead, RevListCount[value=<null>,status=NO_REMOTE,top=<null>] behind, status=NO_REMOTE <> RepoStatus[localHash=c337e5f19cf6610ce42f8e52c44c360c43ab7f9e,localBranch=refs/heads/add-additional-mergefields,remote=RepoStatusRemote[remoteTrackingBranch=<null>,parentBranch=<null>,parentHash=<null>]]
2020-11-12 08:21:09,722 | INFO  | ProjectRepoEventManager        | repository changed
2020-11-12 08:21:09,722 | INFO  | ServerEventManager             | triggering ALL events
2020-11-12 08:21:09,722 | INFO  | ServerEventManager             | triggering event: BUILDS_CHANGED
2020-11-12 08:21:09,722 | INFO  | ServerEventManager             | triggering event: PULL_REQUESTS_CHANGED
2020-11-12 08:21:09,722 | INFO  | ServerEventManager             | triggering event: WORK_ITEMS_CHANGED
2020-11-12 08:21:09,793 | DEBUG | RiderFileBreadcrumbsCollector  | backend breadcrumbs support handles file = true
2020-11-12 08:21:09,793 | DEBUG | RiderFileBreadcrumbsCollector  | start computing crumbs for the file file://D:/Projects/project-name/Core/Processes/AutoDocuments.cs and offset 2836
2020-11-12 08:21:09,921 | INFO  | VcsHelper                      | getRepositoryContext: cache miss: D:/Projects/project-name
2020-11-12 08:21:09,926 | INFO  | BuildStatusLookupOperation     | BuildStatusLookupOperation created.
2020-11-12 08:21:09,928 | INFO  | BuildStatusLookupOperation     | BuildStatusLookupOperation.doWork()
2020-11-12 08:21:09,928 | INFO  | BuildStatusLookupOperation     | getServerContext: url=https://devops-org-name@dev.azure.com/devops-org-name/devops-project-name/_git/project-name
2020-11-12 08:21:09,928 | INFO  | BuildStatusLookupOperation     | getServerContext: forcePrompt=false
2020-11-12 08:21:09,928 | INFO  | BuildStatusLookupOperation     | getServerContext: allowPrompt=false
2020-11-12 08:21:09,943 | WARN  | TeamServicesSecrets            | getServerContextSecrets: info was null for key: 
2020-11-12 08:21:09,944 | WARN  | TeamServicesSecrets            | getServerContextSecrets: info was null for key: 
2020-11-12 08:21:09,944 | INFO  | BuildStatusLookupOperation     | getServerContext: creating GIT context
2020-11-12 08:21:09,944 | WARN  | BuildStatusLookupOperation     | getServerContext: failed to get authenticated server context
2020-11-12 08:21:09,969 | WARN  | CachedStatusCalculator         | Hash mismatch between count and status: RevListCount[value=0,status=SUCCESS,top=<null>] ahead, RevListCount[value=0,status=SUCCESS,top=<null>] behind, status=SUCCESS <> RepoStatus[localHash=95f6d1f6817acd4b11644d0d6fee11ae983553c3,localBranch=refs/heads/master,remote=RepoStatusRemote[remoteTrackingBranch=refs/remotes/origin/master,parentBranch=refs/remotes/origin/master,parentHash=95f6d1f6817acd4b11644d0d6fee11ae983553c3]]
2020-11-12 08:21:09,998 | WARN  | BuildStatusLookupOperation     | doWork: failed with an exception
javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
	at com.microsoft.alm.plugin.operations.Operation.getServerContext(Operation.java:215)
	at com.microsoft.alm.plugin.operations.BuildStatusLookupOperation.doWork(BuildStatusLookupOperation.java:149)
	at com.microsoft.alm.plugin.operations.OperationExecutor$1.run(OperationExecutor.java:56)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-12 08:21:09,999 | INFO  | BuildStatusLookupOperation     | Creating build status results.
2020-11-12 08:21:09,999 | INFO  | BuildStatusLookupOperation     |    builds = null
2020-11-12 08:21:10,115 | DEBUG | RiderFileBreadcrumbsCollector  | backend breadcrumbs support handles file = true
2020-11-12 08:21:10,115 | DEBUG | RiderFileBreadcrumbsCollector  | start computing crumbs for the file file://D:/Projects/project-name/Core/Processes/AutoDocuments.cs and offset 2836
2020-11-12 08:21:10,215 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:10,215 | INFO  | BuildStatusLookupOperation     | BuildStatusLookupOperation created.
2020-11-12 08:21:10,215 | INFO  | BuildStatusLookupOperation     | BuildStatusLookupOperation.doWork()
2020-11-12 08:21:10,215 | INFO  | BuildStatusLookupOperation     | getServerContext: url=https://devops-org-name@dev.azure.com/devops-org-name/devops-project-name/_git/project-name
2020-11-12 08:21:10,215 | INFO  | BuildStatusLookupOperation     | getServerContext: forcePrompt=false
2020-11-12 08:21:10,216 | INFO  | BuildStatusLookupOperation     | getServerContext: allowPrompt=false
2020-11-12 08:21:10,216 | INFO  | BuildStatusLookupOperation     | getServerContext: creating GIT context
2020-11-12 08:21:10,216 | WARN  | BuildStatusLookupOperation     | getServerContext: failed to get authenticated server context
2020-11-12 08:21:10,216 | WARN  | BuildStatusLookupOperation     | doWork: failed with an exception
javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
	at com.microsoft.alm.plugin.operations.Operation.getServerContext(Operation.java:215)
	at com.microsoft.alm.plugin.operations.BuildStatusLookupOperation.doWork(BuildStatusLookupOperation.java:149)
	at com.microsoft.alm.plugin.operations.OperationExecutor$1.run(OperationExecutor.java:56)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-12 08:21:10,216 | INFO  | BuildStatusLookupOperation     | Creating build status results.
2020-11-12 08:21:10,216 | INFO  | BuildStatusLookupOperation     |    builds = null
2020-11-12 08:21:10,387 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:10,393 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:11,120 | INFO  | FileBasedIndexDataInitialization | Initialization done: 3194
2020-11-12 08:21:11,191 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:11,233 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:11,274 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:11,275 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:11,282 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:11,304 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:11,508 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:11,905 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:12,000 | INFO  | StubIndexImpl$StubIndexInitialization | Initialization done: 880
2020-11-12 08:21:13,572 | INFO  | PerformanceWatcher             | Pushing properties took 2441ms; general responsiveness: ok; EDT responsiveness: 2/12 sluggish
2020-11-12 08:21:13,820 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:14,412 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:14,438 | DEBUG | RiderFileBreadcrumbsCollector  | backend breadcrumbs support handles file = true
2020-11-12 08:21:14,439 | DEBUG | RiderFileBreadcrumbsCollector  | start computing crumbs for the file file://D:/Projects/project-name/Core/Processes/AutoDocuments.cs and offset 2836
2020-11-12 08:21:14,499 | INFO  | CloudConfigManager             | === Start.updateConnection ===
2020-11-12 08:21:14,499 | INFO  | CloudConfigManager             | === StatusBar.update another widget: null ===
2020-11-12 08:21:14,499 | INFO  | CloudConfigManager             | === doConnect ===
2020-11-12 08:21:14,499 | INFO  | CloudConfigManager             | === getConnectionState ===
2020-11-12 08:21:14,965 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:15,161 | INFO  | PerformanceWatcher             | Indexable file iteration took 1589ms; general responsiveness: ok; EDT responsiveness: ok
2020-11-12 08:21:15,171 | INFO  | UnindexedFilesUpdater          | Unindexed files update started: 0 files to index
2020-11-12 08:21:15,464 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:15,995 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:16,491 | DEBUG | RiderFileBreadcrumbsCollector  | backend breadcrumbs support handles file = true
2020-11-12 08:21:16,491 | DEBUG | RiderFileBreadcrumbsCollector  | start computing crumbs for the file file://D:/Projects/project-name/Core/Processes/AutoDocuments.cs and offset 3391
2020-11-12 08:21:16,494 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:16,996 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:17,502 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:18,007 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:18,221 | INFO  | CloudConfigManager             | === StatusBar.update another widget: null ===
2020-11-12 08:21:18,222 | INFO  | CloudConfigManager             | === StatusBar.update another widget: null ===
2020-11-12 08:21:18,522 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:19,028 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:19,301 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:19,322 | INFO  | VcsHelper                      | getRepositoryContext: cache hit: D:/Projects/project-name
2020-11-12 08:21:19,342 | INFO  | WorkItemLookupOperation        | WorkItemLookupOperation created.
2020-11-12 08:21:19,344 | INFO  | WorkItemLookupOperation        | WorkItemLookupOperation.doWork()
2020-11-12 08:21:19,345 | INFO  | SelectWorkItemsModel           | WorkItemLookupOperation started.
2020-11-12 08:21:19,345 | INFO  | WorkItemLookupOperation        | getServerContext: url=https://devops-org-name@dev.azure.com/devops-org-name/devops-project-name/_git/project-name
2020-11-12 08:21:19,345 | INFO  | WorkItemLookupOperation        | getServerContext: forcePrompt=false
2020-11-12 08:21:19,345 | INFO  | WorkItemLookupOperation        | getServerContext: allowPrompt=true
2020-11-12 08:21:19,345 | INFO  | WorkItemLookupOperation        | getServerContext: creating GIT context
2020-11-12 08:21:19,346 | INFO  | ServerContextManager           | Prompting for credentials
2020-11-12 08:21:19,346 | INFO  | AuthHelper                     | getAuthenticationInfoSynchronously calling authenticateAsync on https://devops-org-name@dev.azure.com/devops-org-name/devops-project-name/_git/project-name
2020-11-12 08:21:19,352 | INFO  | VsoAuthenticationProvider      | authenticateAsync for server: https://devops-org-name@dev.azure.com/devops-org-name/devops-project-name/_git/project-name
2020-11-12 08:21:19,542 | INFO  | VstsPatAuthenticator           | Signing out from uri: https://app.vssps.visualstudio.com
2020-11-12 08:21:19,545 | INFO  | OAuth2Authenticator            | Ready to launch browser flow to retrieve oauth2 token.
2020-11-12 08:21:19,547 | INFO  | SettingsHelper                 | Searching for C:\Users\local-username\AppData\Local\Microsoft\VstsAuthLib4J\settings.properties
2020-11-12 08:21:19,547 | INFO  | OAuth2Authenticator            | Attempt to use oauth2-useragent provider: none
2020-11-12 08:21:19,547 | INFO  | OAuth2Authenticator            | Fallback to Device Flow.

**Comment by ForNeVeR** [comment]
Is it possible that your password was changed recently?

**Comment by kiaratto** [comment]
I have the same problem when a need push code from intellij, but if I execute  command " Git push  on terminal I don't need login.

But in my case I need login on first time of all operations. Sample: when first push...I need to login, if after I try to get WorkItems...Login Again

**Comment by ForNeVeR** [comment]
@kiaratto, could you check if the IDE password storage works for you? What are the settings at the **Appearance & Behavior → System Settings → Passwords** page?

**Comment by kiaratto** [comment]
> 
> 
> @kiaratto, could you check if the IDE password storage works for you? What are the settings at the **Appearance & Behavior → System Settings → Passwords** page?

kkk Thank You @ForNeVeR - it worked for me !  Sorry for my "junior" question kk

I did not relate the configuration of intellij to the configuration of the plug-in. I thought the plug-in would use git credentials.

Great, tks again !!
