### ISSUE TITLE
KEY_TF_AUTH_FAIL error after upgrading to Rider 2020.3

### ISSUE THREAD

**Issue by streamstr** [microsoft/azure-devops-intellij#413]
Today i've udated Rider to 2020.3
When opened solution from TFVC, got this error:

Error:The TF command line failed to authenticate to the server. Please make sure you have access to the server and/or have entered the correct credentials.

com.microsoft.alm.plugin.external.exceptions.ToolAuthenticationException: KEY_TF_AUTH_FAIL
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.checkErrors(FindWorkspaceCommand.java:119)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:139)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:29)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)

Credentials or server not changed. Also I've reentered credentials in settings with no luck

All works correctly in Rider 2020.2.4

**Comment by ForNeVeR** [comment]
Could you please share the IDE logs? **Help → Collect Logs** in the main menu.

**Comment by streamstr** [comment]
Here they are
[rider-logs-20201216-164551.zip](https://github.com/microsoft/azure-devops-intellij/files/5703108/rider-logs-20201216-164551.zip)

**Comment by ForNeVeR** [comment]
This could indicate a real authentication failure, or bad credentials being passed for some reason. A couple of questions:

1. Could you run `tf.cmd workfold` in your project directory? What will it print?
2. What kind of authentication do you use?

**Comment by streamstr** [comment]
Here is workfold command output:
![image](https://user-images.githubusercontent.com/9412086/102381339-215b8b00-3fda-11eb-83f8-7fc99a977710.png)

I use Windows authentication
I can normally connect to TFS from Visual Studio no matter which Rider version is installed and I have no problems with Rider when I roll back to 2020.2.4

**Comment by streamstr** [comment]
Here is what I see in settings:
![image](https://user-images.githubusercontent.com/9412086/102382629-b317c800-3fdb-11eb-9d1c-5ea7204aaa74.png)
Same VCS mapping that i see in workfold command output (second row)

For some reason there was no mapping, i've added it, but it has red color, meaning something is wrong:
![image](https://user-images.githubusercontent.com/9412086/102382896-f96d2700-3fdb-11eb-8431-23199dbf611b.png)
After doing this, any TFVC command fails silently, not producing error in log.

**Comment by ForNeVeR** [comment]
Could you try to do the following?
1. **Delete configuration** from the screenshot above
2. **Appearance & Behavior | System Settings | Passwords**: press the gear icon and choose **Clear**
   ![image](https://user-images.githubusercontent.com/92793/102455104-99c15b00-4071-11eb-8686-60a0844f7e9d.png)
3. Restart IDE

And then try to clone the repository again, and note if the IDE will ask you for login/password.

**Comment by streamstr** [comment]
Thanks, I'll try to check this later today

**Comment by streamstr** [comment]
I've done what you suggested.
After restarting Rider and opening same solution there was a dialog asking to enter credentials from our TFS server. I entered valid creds, pressed ok. 

Then I've got error in log:
com.microsoft.alm.plugin.external.exceptions.ToolAuthenticationException: KEY_TF_AUTH_FAIL
	at com.microsoft.alm.plugin.external.utils.CommandUtils.getPartialWorkspace(CommandUtils.java:155)
	at com.microsoft.alm.plugin.external.utils.CommandUtils.getPartialWorkspace(CommandUtils.java:109)
	at com.microsoft.alm.plugin.external.utils.CommandUtils.getPartialWorkspace(CommandUtils.java:121)
	at com.microsoft.alm.plugin.idea.tfvc.core.tfs.TFVCUtil.getMappingsFromWorkspace(TFVCUtil.java:111)
	at com.microsoft.alm.plugin.idea.tfvc.core.tfs.TFVCUtil.filterValidTFVCPaths(TFVCUtil.java:78)
	at com.microsoft.alm.plugin.idea.tfvc.core.TFSChangeProvider.getChanges(TFSChangeProvider.java:95)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.actualUpdate(ChangeListManagerImpl.java:685)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.iterateScopes(ChangeListManagerImpl.java:603)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.lambda$updateImmediately$11(ChangeListManagerImpl.java:508)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.lambda$updateImmediately$14(ChangeListManagerImpl.java:507)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$11(BackgroundTaskUtil.java:231)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:230)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl.updateImmediately(ChangeListManagerImpl.java:462)
	at com.intellij.openapi.vcs.changes.UpdateRequestsQueue$MyRunnable.run(UpdateRequestsQueue.java:219)
	at com.intellij.openapi.vcs.changes.ChangeListManagerImpl$MyLoggingRunnable.run(ChangeListManagerImpl.java:1649)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

But from now TFVC actions started to work - I've managed to get latest version, load history and make commit.

What stays unclear for me - why this happened? I did not change my password or other settings like tfs url...

**Comment by ForNeVeR** [comment]
@streamstr, re "what happened": you updated the IDE, and it seems to lose the saved credentials, or something.

Unfortunately, at the moment, I have no on-premise Azure DevOps installation I'd be able to log in via domain credentials to throughly check the issue, but it's probable that the authentication data weren't properly migrated.
