### ISSUE TITLE
Azure DevOps plugin doesn't work with WebStorm 2020.3

### ISSUE THREAD

**Issue by agilim** [microsoft/azure-devops-intellij#414]
Actually I have never been able to get it to work since JetBrains went to 2020 and stopped supporting their older TFS plugin, but 2020.3 is my current release.  It appears to be correctly installed, but when I try to configure it nothing is listed in the configuration management section (see attached screen grab), and I have noticed an IDE fatal error being flagged.  Below is [the]([url](url)) stack trace that error provides.

![image](https://user-images.githubusercontent.com/36666634/102349075-c5105100-3f70-11eb-9a40-26d4cc35b6ea.png)

java.lang.NullPointerException
	at com.microsoft.alm.plugin.external.utils.CommandUtils.getPartialWorkspace(CommandUtils.java:137)
	at com.microsoft.alm.plugin.idea.tfvc.extensions.TfvcRootChecker.lambda$isRoot$1(TfvcRootChecker.java:73)
	at com.microsoft.alm.plugin.idea.tfvc.ui.settings.EULADialog.executeWithGuard(EULADialog.java:226)
	at com.microsoft.alm.plugin.idea.tfvc.extensions.TfvcRootChecker.isRoot(TfvcRootChecker.java:69)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.lambda$getVcsRootFor$4(VcsRootDetectorImpl.java:172)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:55)
	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.java:57)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.getVcsRootFor(VcsRootDetectorImpl.java:171)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.lambda$scanForRootsInsideDir$3(VcsRootDetectorImpl.java:111)
	at com.intellij.openapi.vcs.roots.VcsRootScanner$1.visitFileEx(VcsRootScanner.java:117)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:292)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:324)
	at com.intellij.openapi.vcs.roots.VcsRootScanner.visitDirsRecursivelyWithoutExcluded(VcsRootScanner.java:93)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.scanForRootsInsideDir(VcsRootDetectorImpl.java:106)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.scanForRootsInContentRoots(VcsRootDetectorImpl.java:94)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.detect(VcsRootDetectorImpl.java:41)
	at com.intellij.openapi.vcs.roots.VcsRootErrorsFinder.find(VcsRootErrorsFinder.java:34)
	at com.intellij.openapi.vcs.roots.VcsRootProblemNotifier.scan(VcsRootProblemNotifier.java:196)
	at com.intellij.openapi.vcs.roots.VcsRootProblemNotifier.rescanAndNotifyIfNeeded(VcsRootProblemNotifier.java:71)
	at com.intellij.openapi.vcs.roots.VcsRootScanner.lambda$scheduleScan$2(VcsRootScanner.java:138)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254)
	at com.intellij.openapi.vcs.roots.VcsRootScanner.lambda$scheduleScan$3(VcsRootScanner.java:137)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:372)
	at com.intellij.util.Alarm$Request.run(Alarm.java:358)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by AmrAbdalrahman** [comment]
same with me
Did you solve it?

**Comment by agilim** [comment]
Never did, despite repeated attempts.  Since then, I have retired and am using WebStorm for developing teaching materials and it works just fine with GitHub.  It is unfortunate that Microsoft don’t take better care of their TFS users, because those in corporate environments that use the MS stack have no choice whether to use it or not.
