### ISSUE TITLE
Cant connect to workspace - Newly installed Rider (incompability with TF Anywhere 14.135.0)

### ISSUE THREAD

**Issue by Palku** [microsoft/azure-devops-intellij#415]
If i use TF Anywhere 14.135.0 i cant pick a new workspace.
Workaround downgrade to 14.134.

It works so far that i can list worskspaces and choose the one i want.
![image](https://user-images.githubusercontent.com/10268487/102717523-376f9100-42e3-11eb-9ba8-fd4288a36a0c.png)

But when i take Create Workspace i get this
![image](https://user-images.githubusercontent.com/10268487/102717533-42c2bc80-42e3-11eb-9bce-69fe9ae8f7a5.png)

Logs
2020-12-20 16:37:30,114 | INFO  | ToolRunnerCache                | getRunningToolRunner: toolLocation=/home/pulka/tf/TEE-CLC-14.135.0/tf
2020-12-20 16:37:30,115 | INFO  | ToolRunnerCache                | getRunningToolRunner: slow version - null
2020-12-20 16:37:30,115 | INFO  | ToolRunner                     | ToolRunner.start: toolLocation = /home/pulka/tf/TEE-CLC-14.135.0/tf
2020-12-20 16:37:30,115 | INFO  | ToolRunner                     | ToolRunner.start: workingDirectory = null
2020-12-20 16:37:30,115 | INFO  | ToolRunner                     | arguments: workspace -noprompt -collection:https://seadragon.visualstudio.com ******** -delete Varuregister
2020-12-20 16:37:30,489 | INFO  | Command                        | 0.374518791 sec - elapsed time for workspace -noprompt -collection:https://seadragon.visualstudio.com ******** -delete Varuregister
2020-12-20 16:37:30,489 | WARN  | RiderApplicationLoadListener   | [STDERR] : 0.374518791 sec - elapsed time for workspace -noprompt -collection:https://seadragon.visualstudio.com ******** -delete Varuregister
2020-12-20 16:37:38,590 | INFO  | ServerContextManager           | AuthenticatedInfo found for url https://app.vssps.visualstudio.com
2020-12-20 16:37:38,590 | INFO  | VsoCheckoutPageModel           | Loading contexts in constructor
2020-12-20 16:37:38,590 | INFO  | ServerContextManager           | AuthenticatedInfo found for url https://app.vssps.visualstudio.com
2020-12-20 16:37:38,590 | INFO  | ServerContextManager           | AuthenticatedInfo found for url https://app.vssps.visualstudio.com
2020-12-20 16:37:38,591 | INFO  | ServerContextManager           | AuthenticatedInfo found for url https://app.vssps.visualstudio.com
2020-12-20 16:37:39,216 | INFO  | ServerContextManager           | AuthenticatedInfo found for url https://app.vssps.visualstudio.com
2020-12-20 16:37:39,216 | INFO  | ServerContextManager           | AuthenticatedInfo found for url https://app.vssps.visualstudio.com
2020-12-20 16:37:39,216 | INFO  | ServerContextManager           | AuthenticatedInfo found for url https://app.vssps.visualstudio.com
2020-12-20 16:37:39,216 | INFO  | ServerContextLookupListener    | loadContexts activeOperation with 3 contexts and a scope of PROJECT
2020-12-20 16:37:39,216 | INFO  | ServerContextLookupListener    | loadContexts terminateActiveOperation in state NOT_STARTED
2020-12-20 16:37:39,216 | INFO  | ServerContextLookupListener    | ServerContext operation terminated
2020-12-20 16:37:39,216 | INFO  | ServerContextLookupListener    | ServerContext lookup started
2020-12-20 16:37:39,216 | INFO  | HttpProxyServiceImpl           | useHttpProxy: false
2020-12-20 16:37:39,216 | INFO  | HttpProxyServiceImpl           | useHttpProxy: false
2020-12-20 16:37:39,216 | INFO  | HttpProxyServiceImpl           | useHttpProxy: false
2020-12-20 16:37:40,585 | INFO  | ServerContextLookupListener    | ServerContext lookup results has error: false
2020-12-20 16:37:40,652 | INFO  | ServerContextLookupListener    | ServerContext lookup results has error: false
2020-12-20 16:37:41,083 | INFO  | ServerContextLookupListener    | ServerContext lookup results has error: false
2020-12-20 16:37:41,084 | INFO  | ServerContextLookupListener    | ServerContext lookup completed
2020-12-20 16:37:41,084 | INFO  | ServerContextLookupListener    | ServerContext operation done
2020-12-20 16:37:44,922 | INFO  | FrontendEditorActionHandler    | Executing frontend editor base handler 'EditorBackSpace'
2020-12-20 16:37:45,019 | INFO  | FrontendEditorActionHandler    | Executing frontend editor base handler 'EditorBackSpace'
2020-12-20 16:38:37,252 | INFO  | HttpProxyServiceImpl           | useHttpProxy: false
2020-12-20 16:38:37,819 | INFO  | VstsPatAuthenticator           | Retrieving PersonalAccessToken for uri:https://seadragon.visualstudio.com with name:Azure DevOps IntelliJ Plugin: pulkaman@hotmail.com from: pulkanjaro on: Sun Dec 20 16:38:37 CET 2020, and with scope:, prompt behavior: AUTO
2020-12-20 16:38:38,265 | INFO  | ToolRunnerCache                | getRunningToolRunner: toolLocation=/home/pulka/tf/TEE-CLC-14.135.0/tf
2020-12-20 16:38:38,265 | INFO  | ToolRunnerCache                | getRunningToolRunner: slow version - null
2020-12-20 16:38:38,265 | INFO  | ToolRunner                     | ToolRunner.start: toolLocation = /home/pulka/tf/TEE-CLC-14.135.0/tf
2020-12-20 16:38:38,265 | INFO  | ToolRunner                     | ToolRunner.start: workingDirectory = null
2020-12-20 16:38:38,265 | INFO  | ToolRunner                     | arguments: workspace -noprompt -collection:https://seadragon.visualstudio.com ******** -new -location:local Varuregister -comment:Workspace created through IntelliJ
2020-12-20 16:38:38,271 | WARN  | PerformanceWatcher             | UI was frozen for 1018ms, details saved to /home/pulka/.cache/JetBrains/Rider2020.3/log/threadDumps-freeze-20201220-163838-RD-203.5981.141-SocketInputStream.socketRead0-1sec
2020-12-20 16:38:38,273 | WARN  | AbstractProgressIndicatorBase  | This progress indicator is indeterminate, this may lead to visual inconsistency. Please call setIndeterminate(false) before you start progress.
com.microsoft.alm.plugin.idea.common.utils.IdeaHelper$1.run(IdeaHelper.java:65)
2020-12-20 16:38:38,621 | INFO  | Command                        | 0.355577883 sec - elapsed time for workspace -noprompt -collection:https://seadragon.visualstudio.com ******** -new -location:local Varuregister -comment:Workspace created through IntelliJ
2020-12-20 16:38:38,621 | WARN  | RiderApplicationLoadListener   | [STDERR] : 0.355577883 sec - elapsed time for workspace -noprompt -collection:https://seadragon.visualstudio.com ******** -new -location:local Varuregister -comment:Workspace created through IntelliJ
2020-12-20 16:38:38,621 | INFO  | ToolRunnerCache                | getRunningToolRunner: toolLocation=/home/pulka/tf/TEE-CLC-14.135.0/tf
2020-12-20 16:38:38,621 | INFO  | ToolRunnerCache                | getRunningToolRunner: slow version - null
2020-12-20 16:38:38,621 | INFO  | ToolRunner                     | ToolRunner.start: toolLocation = /home/pulka/tf/TEE-CLC-14.135.0/tf
2020-12-20 16:38:38,621 | INFO  | ToolRunner                     | ToolRunner.start: workingDirectory = null
2020-12-20 16:38:38,621 | INFO  | ToolRunner                     | arguments: workfold -noprompt -collection:https://seadragon.visualstudio.com ******** -map -workspace:Varuregister $/Varuregister /home/pulka/azure/Varuregister
2020-12-20 16:38:38,963 | INFO  | Command                        | ERROR: An argument error occurred: The workspace 'Varuregister' could not be found.
2020-12-20 16:38:38,965 | INFO  | Command                        | CMD: Team Explorer Everywhere Command Line Client (version 14.135.0.202010141426)
2020-12-20 16:38:38,965 | INFO  | Command                        | CMD: 
2020-12-20 16:38:38,965 | INFO  | Command                        | CMD:  workfold command:
2020-12-20 16:38:38,965 | INFO  | Command                        | CMD: 
2020-12-20 16:38:38,965 | INFO  | Command                        | CMD:   Creates, modifies, or displays information about the mappings between your
2020-12-20 16:38:38,965 | INFO  | Command                        | CMD:   workspace folders and the source control server folders to which they
2020-12-20 16:38:38,965 | INFO  | Command                        | CMD:   correspond.
2020-12-20 16:38:38,965 | INFO  | Command                        | CMD: 
2020-12-20 16:38:38,965 | INFO  | Command                        | CMD:  Valid option sets:
2020-12-20 16:38:38,965 | INFO  | Command                        | CMD: 
2020-12-20 16:38:38,978 | INFO  | Command                        | CMD:   workfold [-collection:<url>] [-workspace:<value>] <serverFolder>
2020-12-20 16:38:38,978 | INFO  | Command                        | CMD:   workfold [-map] [-collection:<url>] [-workspace:<value>] <serverFolder>
2020-12-20 16:38:38,978 | INFO  | Command                        | CMD:            <localFolder>
2020-12-20 16:38:38,978 | INFO  | Command                        | CMD:   workfold [-workspace:<value>]
2020-12-20 16:38:38,978 | INFO  | Command                        | CMD:   workfold <localFolder>
2020-12-20 16:38:38,978 | INFO  | Command                        | CMD:   workfold -cloak [-collection:<url>] [-workspace:<value>]
2020-12-20 16:38:38,978 | INFO  | Command                        | CMD:            <serverFolder>|<localFolder>
2020-12-20 16:38:38,978 | INFO  | Command                        | CMD:   workfold -decloak [-collection:<url>] [-workspace:<value>]
2020-12-20 16:38:38,978 | INFO  | Command                        | CMD:            <serverFolder>|<localFolder>
2020-12-20 16:38:38,978 | INFO  | Command                        | CMD:   workfold -unmap [-collection:<url>] [-workspace:<value>]
2020-12-20 16:38:38,978 | INFO  | Command                        | CMD:            <serverFolder>|<localFolder>
2020-12-20 16:38:38,978 | INFO  | Command                        | CMD: 
2020-12-20 16:38:38,996 | WARN  | Command                        | CMD: parsing output failed
java.lang.RuntimeException: An argument error occurred: The workspace 'Varuregister' could not be found.

	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:438)
	at com.microsoft.alm.plugin.external.commands.UpdateWorkspaceMappingCommand.parseOutput(UpdateWorkspaceMappingCommand.java:85)
	at com.microsoft.alm.plugin.external.commands.UpdateWorkspaceMappingCommand.parseOutput(UpdateWorkspaceMappingCommand.java:21)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:295)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:333)
2020-12-20 16:38:38,996 | WARN  | Command                        | Error: java.lang.RuntimeException: An argument error occurred: The workspace 'Varuregister' could not be found.

Sync stack trace: java.base/java.lang.Thread.getStackTrace(Thread.java:1607)
    at com.microsoft.alm.plugin.external.commands.Command.runSynchronously(Command.java:243)
    at com.microsoft.alm.plugin.idea.tfvc.ui.checkout.TfvcCheckoutModel$1.run(TfvcCheckoutModel.java:113)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.base/java.lang.Thread.run(Thread.java:834)
2020-12-20 16:38:38,996 | INFO  | Command                        | 0.375242777 sec - elapsed time for workfold -noprompt -collection:https://seadragon.visualstudio.com ******** -map -workspace:Varuregister $/Varuregister /home/pulka/azure/Varuregister
2020-12-20 16:38:38,996 | WARN  | RiderApplicationLoadListener   | [STDERR] : 0.375242777 sec - elapsed time for workfold -noprompt -collection:https://seadragon.visualstudio.com ******** -map -workspace:Varuregister $/Varuregister /home/pulka/azure/Varuregister
2020-12-20 16:38:38,996 | WARN  | TfvcCheckoutModel              | Error while mapping workspace during creation
java.lang.RuntimeException: An argument error occurred: The workspace 'Varuregister' could not be found.

**Comment by snoopiedoom** [comment]
Not sure if I'm kicking in the dark, but I have a similar error:
```
com.microsoft.alm.plugin.external.exceptions.ToolBadExitCodeException: KEY_TF_BAD_EXIT_CODE
	at com.microsoft.alm.plugin.external.tools.TfTool.throwBadExitCode(TfTool.java:119)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:185)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:306)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:344)
2023-09-05 15:32:19,860 [  70676]   INFO - com.microsoft.alm.plugin.external.commands.Command - ERROR: An argument error occurred: The workspace '123000409IE1' could not be found.
```

And based on this [post](https://stackoverflow.com/questions/4863865/unable-to-determine-the-workspace-using-tf-exe#:~:text=From%20Forums%20MSDN,workspace%20is%20mapped) I fiddled around a bit:
```
PS C:\Dev\Software\Main> tf workfold
Default credentials are unavailable because no Kerberos ticket or other authentication token is available.
Username: imnottelling
Password: almostposted

==================================================================================================================
Workspace:  123000409IE1
Collection: http://sistemisvr3.iskraemeco.si:8080/tfs/
 $/Software/SEP2W System/Dev/Dev SLA: C:\Dev\Software\Dev SLA
 $/Software/SEP2W System/Main: C:\Dev\Software\Main
 $/Software/SEP2W System/Release/3.16: C:\Dev\Software\3.16
 $/Software/SEP2W System/Release/3.18: C:\Dev\Software\3.18

PS C:\Dev\Software\Main> cd ..
PS C:\Dev\Software> tf workfold
An argument error occurred: The workspace could not be determined from any argument paths or the current working directory.
Team Explorer Everywhere Command Line Client (version 14.135.3.202111260708)

 workfold command:

  Creates, modifies, or displays information about the mappings between your workspace folders and the source control server folders to which they
  correspond.

 Valid option sets:

  workfold /cloak [/collection:<url>] [/workspace:<value>] <serverFolder>|<localFolder>
  workfold /decloak [/collection:<url>] [/workspace:<value>] <serverFolder>|<localFolder>
  workfold /unmap [/collection:<url>] [/workspace:<value>] <serverFolder>|<localFolder>
  workfold [/collection:<url>] [/workspace:<value>] <serverFolder>
  workfold [/map] [/collection:<url>] [/workspace:<value>] <serverFolder> <localFolder>
  workfold [/workspace:<value>]
  workfold <localFolder>

NativeCommandExitException: Program "tf.cmd" ended with non-zero exit code: 100.
```

```
2023-09-05 15:32:19,589 [  70405]   INFO - com.microsoft.alm.plugin.external.ToolRunner - ToolRunner.start: toolLocation = C:\Dev\Sandbox\TEE-CLC-14.135.3\tf.cmd
2023-09-05 15:32:19,592 [  70408]   INFO - com.microsoft.alm.plugin.external.ToolRunner - ToolRunner.start: workingDirectory = null
2023-09-05 15:32:19,612 [  70428]   INFO - com.microsoft.alm.plugin.external.ToolRunner - arguments: @
2023-09-05 15:32:19,782 [  70598]   WARN - com.microsoft.alm.plugin.external.commands.Command - CMD: parsing output failed
com.microsoft.alm.plugin.external.exceptions.ToolBadExitCodeException: KEY_TF_BAD_EXIT_CODE
	at com.microsoft.alm.plugin.external.tools.TfTool.throwBadExitCode(TfTool.java:119)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:185)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:306)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:344)
2023-09-05 15:32:19,860 [  70676]   INFO - com.microsoft.alm.plugin.external.commands.Command - ERROR: An argument error occurred: The workspace '123000409IE1' could not be found.
```

Second line says workingDirectory = null so I'm wondering if maybe tf is in the wrong execution folder ? @ForNeVeR 

[idea.zip](https://github.com/microsoft/azure-devops-intellij/files/12524518/idea.zip)

**Comment by ForNeVeR** [comment]
@snoopiedoom, in your case, the actual output of the program seems to be `The workspace '123000409IE1' could not be found.`

Could you try running command the same way it goes in the logs?

**Comment by snoopiedoom** [comment]
I see that that I'm a bit lost, running resolvePath:
```
PS C:\Dev\Software\Main> tf resolvePath -noprompt -collection:http://sistemisvr3.iskraemeco.si:8080/tfs/DefaultCollection ******** $/Software/SEP2W System/Main/Symbiot/Symbiot.Reactor/Reactor/app.config -workspace:123000409IE1
An argument error occurred: resolvePath requires exactly one path argument.
Team Explorer Everywhere Command Line Client (version 14.135.3.202111260708)

 resolvePath command:

  Translate server paths to local paths. Empty string is returned if the server path is not mapped.

 Valid option sets:

  resolvePath [/collection:<url>] [/workspace:<value>] <serverPath>
  resolvePath <serverPath>

NativeCommandExitException: Program "tf.cmd" ended with non-zero exit code: 100.
```

and windows tf.exe:
```
c:\Dev\Software\Main>tf resolvePath -noprompt -collection:http://sistemisvr3.iskraemeco.si:8080/tfs/DefaultCollection ******** $/Software/SEP2W System/Main/Symbiot/Symbiot.Reactor/Reactor/app.config -workspace:123000409IE1
Too many items specified.
```
