### ISSUE TITLE
Exception occurred when importing repository from TFS with Jetbrain Rider

### ISSUE THREAD

**Issue by naichuan-zhang** [microsoft/azure-devops-intellij#417]
com.microsoft.alm.plugin.external.exceptions.ToolException: KEY_TF_HOME_NOT_SET
	at com.microsoft.alm.plugin.external.tools.TfTool.getValidLocation(TfTool.java:64)
	at com.microsoft.alm.plugin.external.commands.Command.run(Command.java:143)
	at com.microsoft.alm.plugin.external.commands.Command.runSynchronously(Command.java:223)
	at com.microsoft.alm.plugin.external.utils.CommandUtils.getPartialWorkspace(CommandUtils.java:136)
	at com.microsoft.alm.plugin.external.utils.CommandUtils.getPartialWorkspace(CommandUtils.java:169)
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcIntegrationEnabler.determineWorkspaceDirectory(TfvcIntegrationEnabler.java:138)
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcIntegrationEnabler.access$000(TfvcIntegrationEnabler.java:58)
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcIntegrationEnabler$1.run(TfvcIntegrationEnabler.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:520)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:79)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ForNeVeR** [comment]
While this definitely is not right (to throw an exception, I mean), this likely just mean you haven't enabled the TFVC client in its settings.
