### ISSUE TITLE
Importing project from the Android Studio start page fails with exception

### ISSUE THREAD

**Issue by markorakita** [microsoft/azure-devops-intellij#431]
If you try to clone the project from the start screen like this:

![devops_plugin_bug_1](https://user-images.githubusercontent.com/25534110/115123668-64486200-9fbe-11eb-8d71-a2df6640ab00.png)

![devops_plugin_bug_2](https://user-images.githubusercontent.com/25534110/115123731-a83b6700-9fbe-11eb-83eb-fd5080e1c180.png)

and then you click "Clone", and authenticate with Microsoft account to Azure DevOps, and choose the project, and start cloning it: it will fail with some big exception that starts with "Clone failed" and ends with this at the bottom "Authentication failed".

But if you first open some other project inside Android Studio, and then you go to "File -> New -> Project from Version Control", and do all the same steps as above: project will be successfully cloned.

**Comment by markorakita** [comment]
I've dug some related logs from idea log file:

2021-04-17 18:41:46,760 [ 178246]   INFO -  #git4idea.commands.GitHandler - java.lang.RuntimeException: Invocation failed Unexpected end of file from server 
2021-04-17 18:41:46,761 [ 178247]   INFO -  #git4idea.commands.GitHandler - at org.jetbrains.git4idea.http.GitAskPassXmlRpcClient.askPassword(GitAskPassXmlRpcClient.java:70) 
2021-04-17 18:41:46,761 [ 178247]   INFO -  #git4idea.commands.GitHandler - at org.jetbrains.git4idea.http.GitAskPassApp.main(GitAskPassApp.java:70) 
2021-04-17 18:41:46,761 [ 178247]   INFO -  #git4idea.commands.GitHandler - Caused by: java.net.SocketException: Unexpected end of file from server 
2021-04-17 18:41:46,762 [ 178248]   INFO -  #git4idea.commands.GitHandler - at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851) 
2021-04-17 18:41:46,762 [ 178248]   INFO -  #git4idea.commands.GitHandler - at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) 
2021-04-17 18:41:46,762 [ 178248]   INFO -  #git4idea.commands.GitHandler - at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:848) 
2021-04-17 18:41:46,762 [ 178248]   INFO -  #git4idea.commands.GitHandler - at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) 
2021-04-17 18:41:46,762 [ 178248]   INFO -  #git4idea.commands.GitHandler - at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593) 
2021-04-17 18:41:46,762 [ 178248]   INFO -  #git4idea.commands.GitHandler - at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) 
2021-04-17 18:41:46,762 [ 178248]   INFO -  #git4idea.commands.GitHandler - at org.apache.xmlrpc.DefaultXmlRpcTransport.sendXmlRpc(DefaultXmlRpcTransport.java:87) 
2021-04-17 18:41:46,762 [ 178248]   INFO -  #git4idea.commands.GitHandler - at org.apache.xmlrpc.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:72) 
2021-04-17 18:41:46,762 [ 178248]   INFO -  #git4idea.commands.GitHandler - at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:194) 
2021-04-17 18:41:46,762 [ 178248]  ERROR - jetbrains.ide.XmlRpcServerImpl - Last Action: Vcs.VcsClone 
2021-04-17 18:41:46,762 [ 178248]   INFO -  #git4idea.commands.GitHandler - at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:185) 
2021-04-17 18:41:46,762 [ 178248]   INFO -  #git4idea.commands.GitHandler - at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:178) 
2021-04-17 18:41:46,763 [ 178249]   INFO -  #git4idea.commands.GitHandler - at org.jetbrains.git4idea.http.GitAskPassXmlRpcClient.askPassword(GitAskPassXmlRpcClient.java:67) 
2021-04-17 18:41:46,763 [ 178249]   INFO -  #git4idea.commands.GitHandler - ... 1 more 
2021-04-17 18:41:46,928 [ 178414]   INFO -  #git4idea.commands.GitHandler - fatal: Authentication failed for '<repo path retracted>'

**Comment by markorakita** [comment]
Some more related logs:

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.ide.XmlRpcServerImpl.invoke(XmlRpcServerImpl.java:180)
	at org.jetbrains.ide.XmlRpcServerImpl.invokeHandler(XmlRpcServerImpl.java:141)
	at org.jetbrains.ide.XmlRpcServerImpl.process(XmlRpcServerImpl.java:101)
	at org.jetbrains.ide.XmlRpcServerImpl$XmlRpcRequestHandler.process(XmlRpcServerImpl.java:58)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:28)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$2.test(DelegatingHttpRequestHandler.kt:52)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$2.test(DelegatingHttpRequestHandler.kt:23)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.lambda$findFirstSafe$0(ExtensionProcessingHelper.java:34)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:45)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.findFirstSafe(ExtensionProcessingHelper.java:34)
	at com.intellij.openapi.extensions.ExtensionPointName.findFirstSafe(ExtensionPointName.java:54)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.kt:51)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:15)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:11)
	at org.jetbrains.io.SimpleChannelInboundHandlerAdapter.channelRead0(SimpleChannelInboundHandlerAdapter.java:21)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.jetbrains.io.PortUnificationServerHandler.decode(PortUnificationServerHandler.java:133)
	at org.jetbrains.io.PortUnificationServerHandler.messageReceived(PortUnificationServerHandler.java:80)
	at org.jetbrains.io.Decoder.channelRead(Decoder.java:24)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at com.intellij.dvcs.repo.VcsRepositoryManager.getInstance(VcsRepositoryManager.java:53)
	at com.intellij.dvcs.repo.AbstractRepositoryManager.<init>(AbstractRepositoryManager.java:25)
	at git4idea.repo.GitRepositoryManager.<init>(GitRepositoryManager.java:43)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:53)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:660)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:54)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:411)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:394)
	at com.intellij.openapi.project.impl.DefaultProject.getService(DefaultProject.java:227)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:24)
	at git4idea.repo.GitRepositoryManager.getInstance(GitRepositoryManager.java:56)
	at git4idea.GitUtil.getRepositoryManager(GitUtil.java:640)
	at com.microsoft.alm.plugin.idea.git.utils.TfGitHelper.getTfGitRemotes(TfGitHelper.java:87)
	at com.microsoft.alm.plugin.idea.git.extensions.TfGitHttpAuthDataProvider.tryDetectApiUriFromGitRemotes(TfGitHttpAuthDataProvider.java:49)
	at com.microsoft.alm.plugin.idea.git.extensions.TfGitHttpAuthDataProvider.getAuthData(TfGitHttpAuthDataProvider.java:89)
	at git4idea.remote.GitHttpAuthDataProvider.getAuthData(GitHttpAuthDataProvider.java:36)
	at git4idea.commands.GitHttpGuiAuthenticator$ExtensionAdapterProvider.getDataForKnownLogin(GitHttpGuiAuthenticator.java:304)
	at git4idea.commands.GitHttpGuiAuthenticator.lambda$askPassword$1(GitHttpGuiAuthenticator.java:102)
	at git4idea.commands.GitHttpGuiAuthenticator.lambda$acquireData$2(GitHttpGuiAuthenticator.java:139)
	at git4idea.commands.GitPassthroughAuthenticationGate.waitAndCompute(GitAuthenticationGates.kt:52)
	at git4idea.commands.GitHttpGuiAuthenticator.acquireData(GitHttpGuiAuthenticator.java:136)
	at git4idea.commands.GitHttpGuiAuthenticator.askPassword(GitHttpGuiAuthenticator.java:102)
	at git4idea.commands.GitHttpAuthService$InternalRequestHandlerDelegate.lambda$askPassword$1(GitHttpAuthService.java:73)
	at git4idea.commands.GitHttpAuthService.getDefaultValueIfCancelled(GitHttpAuthService.java:80)
	at git4idea.commands.GitHttpAuthService$InternalRequestHandlerDelegate.askPassword(GitHttpAuthService.java:73)
	... 55 more
```

**Comment by askerasadov** [comment]
Hello, have the same issue

**Comment by mariuspena** [comment]
Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
Runtime version: 11.0.11+0-b60-7772763 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 10
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.microsoft.vso.idea (1.162.0)

git version 2.32.0 (Apple Git-132)

Azure DevOps plugin (for Android Studio) - version 1.162.0

1. Installed plugin in android studio
2. clicked Get from VCS
3. selected Azure Devops Git
4. Azure Devops Services window opens and I click sign in
5. A code is generated and I am asked to go to https://microsoft.com/devicelogin
6. I input the code there and I return to android studio
7. I am authenticated and I see a list of repos (I can also search/filter them)

Problem: Whatever repo I select and then click on Clone button nothing happens. Sometimes it freezes, sometimes I can still click cancel, no repo is cloned. I caught this error below in the android studio error window/logs: 

`java.lang.Error: java.io.IOException: HTTP request failed with code 400: {"$id":"1","innerException":null,"message":"FullScopePatPolicyViolation","typeName":"Microsoft.VisualStudio.Services.DelegatedAuthorization.SessionTokenCreateException, Microsoft.VisualStudio.Services.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"SessionTokenCreateException","errorCode":0,"eventId":3000}

	at com.microsoft.alm.auth.pat.VsoAzureAuthority.generatePersonalAccessToken(VsoAzureAuthority.java:79)
	at com.microsoft.alm.auth.pat.VstsPatAuthenticator$1.doRetrieve(VstsPatAuthenticator.java:195)
	at com.microsoft.alm.auth.pat.VstsPatAuthenticator$1.doRetrieve(VstsPatAuthenticator.java:157)
	at com.microsoft.alm.auth.BaseAuthenticator$SecretRetriever.retrieve(BaseAuthenticator.java:268)
	at com.microsoft.alm.auth.pat.VstsPatAuthenticator.getToken(VstsPatAuthenticator.java:202)
	at com.microsoft.alm.auth.pat.VstsPatAuthenticator.getPersonalAccessToken(VstsPatAuthenticator.java:142)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfo(VsoAuthInfoProvider.java:138)
	at com.microsoft.alm.plugin.idea.common.ui.common.LoginPageModelImpl.completeSignIn(LoginPageModelImpl.java:51)
	at com.microsoft.alm.plugin.idea.common.ui.checkout.CheckoutPageModelImpl.cloneSelectedRepo(CheckoutPageModelImpl.java:273)
	at com.microsoft.alm.plugin.idea.common.ui.checkout.CheckoutController.cloneRepo(CheckoutController.java:136)
	at com.microsoft.alm.plugin.idea.common.ui.checkout.CheckoutController.access$000(CheckoutController.java:28)
	at com.microsoft.alm.plugin.idea.common.ui.checkout.CheckoutController$1.actionPerformed(CheckoutController.java:109)
	at com.microsoft.alm.plugin.idea.common.ui.common.ActionListenerContainer.triggerEvent(ActionListenerContainer.java:15)
	at com.microsoft.alm.plugin.idea.common.ui.common.ActionListenerContainer.triggerEvent(ActionListenerContainer.java:20)
	at com.microsoft.alm.plugin.idea.common.ui.common.BaseDialogImpl.doOKAction(BaseDialogImpl.java:110)
	at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1887)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1840)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:436)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1702)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1661)
	at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1675)
	at com.microsoft.alm.plugin.idea.common.ui.common.BaseDialogImpl.showModalDialog(BaseDialogImpl.java:192)
	at com.microsoft.alm.plugin.idea.common.ui.checkout.CheckoutController.showModalDialog(CheckoutController.java:75)
	at com.microsoft.alm.plugin.idea.git.extensions.GitCheckoutProvider.doCheckout(GitCheckoutProvider.java:39)
	at com.intellij.openapi.vcs.ui.VcsCloneComponentStub.doClone(VcsCloneComponentStub.kt:32)
	at com.intellij.util.ui.cloneDialog.RepositoryUrlCloneDialogExtension$RepositoryUrlMainExtensionComponent.doClone(RepositoryUrlCloneDialogExtension.kt:106)
	at com.intellij.util.ui.cloneDialog.VcsCloneDialog.doClone(VcsCloneDialog.kt:87)
	at com.intellij.openapi.wm.impl.welcomeScreen.GetFromVersionControlAction.actionPerformed(GetFromVersionControlAction.kt:44)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:267)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil.performAnActionForComponent(WelcomeScreenActionsUtil.java:96)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil$LargeIconWithTextWrapper.lambda$new$0(WelcomeScreenActionsUtil.java:125)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.io.IOException: HTTP request failed with code 400: {"$id":"1","innerException":null,"message":"FullScopePatPolicyViolation","typeName":"Microsoft.VisualStudio.Services.DelegatedAuthorization.SessionTokenCreateException, Microsoft.VisualStudio.Services.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"SessionTokenCreateException","errorCode":0,"eventId":3000}

	at com.microsoft.alm.helpers.HttpClientImpl.ensureOK(HttpClientImpl.java:41)
	at com.microsoft.alm.helpers.HttpClientImpl.getPostResponseText(HttpClientImpl.java:186)
	at com.microsoft.alm.auth.pat.VsoAzureAuthority.generatePersonalAccessToken(VsoAzureAuthority.java:69)
	... 126 more`

**Comment by connorjs** [comment]
I recommend closing issues related to `FullScopePatPolicyViolation` in favor of #481 which, at time of writing, has the most up votes. Let's focus the discussion there.
