### ISSUE TITLE
In IDEA 2021.1.1

### ISSUE THREAD

**Issue by shaokuuipo** [microsoft/azure-devops-intellij#436]
com.microsoft.alm.plugin.external.exceptions.ToolException: KEY_TF_EXE_NOT_FOUND
	at com.microsoft.alm.plugin.external.tools.TfTool.getValidLocation(TfTool.java:80)
	at com.microsoft.alm.plugin.external.commands.Command.run(Command.java:143)
	at com.microsoft.alm.plugin.external.commands.Command.runSynchronously(Command.java:223)
	at com.microsoft.alm.plugin.idea.tfvc.ui.settings.EULADialog.executeWithGuard(EULADialog.java:226)
	at com.microsoft.alm.plugin.idea.tfvc.ui.checkout.TfvcCheckoutModel$1.run(TfvcCheckoutModel.java:91)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ForNeVeR** [comment]
Hello. Have you set up a TFVC client in the IDE settings?

**Comment by shaokuuipo** [comment]
I set TEE-CLC-14.135.0

**Comment by ForNeVeR** [comment]
@shaokuuipo, and you still experience the issue? Could you please show a settings screenshot?

**Comment by shaokuuipo** [comment]
Only set TEE-CLC-14.135.0 . Visual Studio TF Client not set.
Thanks for your help!!!

![1](https://user-images.githubusercontent.com/5934827/118934346-daa10100-b97c-11eb-942e-5fb8232dc746.png)
![2](https://user-images.githubusercontent.com/5934827/118934379-e260a580-b97c-11eb-9e7e-8976e2ff021e.png)
![3](https://user-images.githubusercontent.com/5934827/118934390-e55b9600-b97c-11eb-9a5d-ab3e52f87db1.png)

**Comment by ForNeVeR** [comment]
You should set it as the full path to the `tf.cmd` file, not to the directory.

That's a valid point, though. The plugin could've guessed the name of the executable after you selected the directory.

For now, try `D:\developer\TEE-CLC-14.135.0\tf.cmd`, it should work.

**Comment by shaokuuipo** [comment]
It's worked, thank you.

**Comment by ForNeVeR** [comment]
I'll keep the issue open and transform it into a feature request: let's allow the users to choose the TFVC client directory in settings, and detect the executable file (`tf` or `tf.cmd`) automatically.
