### ISSUE TITLE
Rider - plugin IDE error

### ISSUE THREAD

**Issue by Koochy87** [microsoft/azure-devops-intellij#453]
Hi,

last days I'm still seeing this type of error on Rider from AzureDevOps plugin:

com.microsoft.alm.plugin.external.exceptions.WorkspaceCouldNotBeDeterminedException: KEY_TF_WORKSPACE_COULD_NOT_BE_DETERMINED
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.checkErrors(FindWorkspaceCommand.java:121)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:139)
	at com.microsoft.alm.plugin.external.commands.FindWorkspaceCommand.parseOutput(FindWorkspaceCommand.java:29)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:178)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:306)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:344)

Do you have any suggestions to fix the error or prevent from it?

**Comment by ForNeVeR** [comment]
Could you please provide IDE logs?

**Comment by Koochy87** [comment]
Sure, it is a 28 MB zip file. I can not post it here. Is there any file-pipeline to this purpose?

**Comment by ForNeVeR** [comment]
Please send it to my work email `ivan.migalev@jetbrains.com`
