### ISSUE TITLE
Issue with Rider and Local Install of Azure Devops

### ISSUE THREAD

**Issue by milkteacactuar** [microsoft/azure-devops-intellij#456]
Forgive me if this is not the right repo for this report, or if it's not an issue and it's my ignorance. When I try to connect via the plugin I get an error: Unable to connect to Team Foundation Server 'https://localtfs'. Verify access to the server URL and try 'Connect...' again.

This happens after I:
1) Install the plugin
2) vcs -> import into azure devops service git -> click tfs tab -> enter my url
3) at user name and password pop up enter user and password.

I tried to update the cert bundle for git and also for the jre that was installed with azure devops although I'm not sure if this actually a certificate issue or not.

**Comment by milkteacactuar** [comment]
Update, I found where the logs are in another issue you responded to and it looks like it is just reporting connection reset.

2021-09-20 21:50:33,483 | INFO  | TfsAuthenticationProvider      | starting TfsAuthenticator
2021-09-20 21:50:33,484 | INFO  | TfsAuthenticationProvider      | Async authentication starting
2021-09-20 21:50:34,783 | INFO  | ServerPollingManager           | Timer fired
2021-09-20 21:50:34,783 | INFO  | ServerEventManager             | triggering ALL events
2021-09-20 21:50:34,783 | INFO  | ServerEventManager             | triggering event: BUILDS_CHANGED
2021-09-20 21:50:34,783 | INFO  | ServerEventManager             | triggering event: PULL_REQUESTS_CHANGED
2021-09-20 21:50:34,783 | INFO  | ServerEventManager             | triggering event: WORK_ITEMS_CHANGED
2021-09-20 21:50:37,405 | INFO  | ServerContextManager           | Validating a TFS server context with a server URI https://purgatory
2021-09-20 21:50:37,405 | INFO  | HttpProxyServiceImpl           | useHttpProxy: false
2021-09-20 21:50:37,429 | INFO  | TfsAuthenticationProvider      | Async authentication done - result: false
2021-09-20 21:50:37,431 | WARN  | LookupHelper                   | Connecting to TFS server failed
javax.ws.rs.ProcessingException: javax.net.ssl.SSLException: Connection reset
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:472)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:254)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:729)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:728)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:395)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:295)
	at com.microsoft.alm.plugin.context.rest.VstsHttpClient.sendRequest(VstsHttpClient.java:33)
	at com.microsoft.alm.plugin.context.ServerContextManager.checkTfsVersionAndConnection(ServerContextManager.java:275)
	at com.microsoft.alm.plugin.context.ServerContextManager.validateServerConnection(ServerContextManager.java:232)
	at com.microsoft.alm.plugin.context.ServerContextManager.validateServerConnection(ServerContextManager.java:191)
	at com.microsoft.alm.plugin.idea.common.services.CredentialsPromptImpl.validateCredentials(CredentialsPromptImpl.java:68)
	at com.microsoft.alm.plugin.authentication.TfsAuthenticationProvider$TfsAuthenticator.run(TfsAuthenticationProvider.java:112)
Caused by: javax.net.ssl.SSLException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:144)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1418)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1324)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:426)
	... 15 more
	Suppressed: java.net.SocketException: Connection reset by peer: socket write error
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:380)
		... 34 more
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	... 31 more

**Comment by milkteacactuar** [comment]
Failing with most recent windows 11 build, works on fresh install of windows 10 and fresh install of rider.
