### ISSUE TITLE
error in resolve conflict

### ISSUE THREAD

**Issue by mohammadghari1376** [microsoft/azure-devops-intellij#473]
**Hi 
my ide make exception when my version and server version is in conflict

please help me**

```

java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.alm.plugin.idea.tfvc.core.tfs.conflicts.ConflictsEnvironment
at com.microsoft.alm.plugin.idea.tfvc.core.TFSUpdateEnvironment.updateDirectories(TFSUpdateEnvironment.java:107)
at com.intellij.openapi.vcs.update.AbstractCommonUpdateAction$Updater.performUpdate(AbstractCommonUpdateAction.java:389)
at com.intellij.openapi.vcs.update.AbstractCommonUpdateAction$Updater.runImpl(AbstractCommonUpdateAction.java:358)
at com.intellij.openapi.vcs.update.AbstractCommonUpdateAction$Updater.run(AbstractCommonUpdateAction.java:332)
at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:238)
at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:238)
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
at java.base/java.lang.Thread.run(Thread.java:829)



java.lang.NoClassDefFoundError: com/intellij/openapi/diff/DiffRequest
	at com.microsoft.alm.plugin.idea.tfvc.core.tfs.conflicts.ConflictsEnvironment.<clinit>(ConflictsEnvironment.java:27)
	at com.microsoft.alm.plugin.idea.tfvc.core.TFSUpdateEnvironment.updateDirectories(TFSUpdateEnvironment.java:107)
	at com.intellij.openapi.vcs.update.AbstractCommonUpdateAction$Updater.performUpdate(AbstractCommonUpdateAction.java:389)
	at com.intellij.openapi.vcs.update.AbstractCommonUpdateAction$Updater.runImpl(AbstractCommonUpdateAction.java:358)
	at com.intellij.openapi.vcs.update.AbstractCommonUpdateAction$Updater.run(AbstractCommonUpdateAction.java:332)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
	at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:238)
	at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:238)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.intellij.openapi.diff.DiffRequest PluginClassLoader(plugin=PluginDescriptor(name=Azure DevOps, id=com.microsoft.vso.idea, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\Rider2021.3\plugins\com.microsoft.vso.idea, version=1.162.0, package=null, isBundled=false), packagePrefix=null, instanceId=90, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 27 more
```

**Comment by mohammadghari1376** [comment]
java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.alm.plugin.idea.tfvc.core.tfs.conflicts.ConflictsEnvironment
	at com.microsoft.alm.plugin.idea.tfvc.core.TFSUpdateEnvironment.updateDirectories(TFSUpdateEnvironment.java:107)
	at com.intellij.openapi.vcs.update.AbstractCommonUpdateAction$Updater.performUpdate(AbstractCommonUpdateAction.java:389)
	at com.intellij.openapi.vcs.update.AbstractCommonUpdateAction$Updater.runImpl(AbstractCommonUpdateAction.java:358)
	at com.intellij.openapi.vcs.update.AbstractCommonUpdateAction$Updater.run(AbstractCommonUpdateAction.java:332)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
	at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:238)
	at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:238)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by ForNeVeR** [comment]
Which IDE version is this?

**Comment by mohammadghari1376** [comment]
![image](https://user-images.githubusercontent.com/47270933/150924566-bfedbd61-ba1c-45e7-bda3-edbc7ffb1039.png)

**Comment by mohammadghari1376** [comment]
Thanks for checking and fixing the bug.
When can I get this item from the Rider plugins section?
