### ISSUE TITLE
Cannot get data from Azure repo on WebStorm MacOs

### ISSUE THREAD

**Issue by bezgemeo** [microsoft/azure-devops-intellij#477]
I'm trying to clone a repo on MacOs WebStorm and installed for these purposes Azure Devops plugin. But it is not allowing me to clone anything, throwing this:

```
java.lang.RuntimeException: Error: Could not find or load main class com.microsoft.tfs.client.clc.vc.Main
Caused by: java.lang.ClassNotFoundException: com.microsoft.tfs.client.clc.vc.Main

	at com.microsoft.alm.plugin.external.commands.Command.throwIfError(Command.java:448)
	at com.microsoft.alm.plugin.external.commands.TfVersionCommand.parseOutput(TfVersionCommand.java:36)
	at com.microsoft.alm.plugin.external.commands.TfVersionCommand.parseOutput(TfVersionCommand.java:15)
	at com.microsoft.alm.plugin.external.commands.Command$1.completed(Command.java:183)
	at com.microsoft.alm.plugin.external.ToolRunner$ListenerProxy.completed(ToolRunner.java:306)
	at com.microsoft.alm.plugin.external.ToolRunner$ProcessWaiter.run(ToolRunner.java:344)
```

and also it requires from me installing for the command line tool, which I've downloaded and it is also throwing an error
![image](https://user-images.githubusercontent.com/24274686/152977658-856f39b9-bef9-4043-b3dd-71af516f7919.png)

How that could be fixed?

**Comment by ForNeVeR** [comment]
Could you please call the command-line tool from the terminal and show the output?
