### ISSUE TITLE
M1 Support?

### ISSUE THREAD

**Issue by bk-tfo** [microsoft/azure-devops-intellij#490]
I am getting the following traceback on macOS, using Rider Build `RD-221.5591.20`, runtime is `11.0.14.1+1-b2043.45 aarch64`:

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.jetbrains.rd.util.reactive.RdFault: /Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp: dlopen(/Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp, 0x0001): tried: '/Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), reason: java.lang.UnsatisfiedLinkError: /Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp: dlopen(/Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp, 0x0001): tried: '/Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e'))
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.microsoft.tfs.jni.internal.unix.macos.LibC.<clinit>(LibC.java:8)
	at com.microsoft.tfs.jni.internal.platformmisc.MacOsNativePlatformMisc.<clinit>(MacOsNativePlatformMisc.java:11)
	at com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.<init>(NativePlatformMisc.java:27)
	at com.microsoft.tfs.jni.PlatformMiscUtils.<init>(PlatformMiscUtils.java:22)
	at com.microsoft.tfs.jni.PlatformMiscUtils.<clinit>(PlatformMiscUtils.java:9)
	at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.makeDirectoryForVendorApplicationVersion(VersionedVendorFilesystemPersistenceStore.java:97)
	at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.<init>(VersionedVendorFilesystemPersistenceStore.java:60)
	at com.microsoft.tfs.core.config.persistence.DefaultPersistenceStoreProvider.<clinit>(DefaultPersistenceStoreProvider.java:42)
	at com.microsoft.tfs.TfsClient$Companion.tryLoadWorkspaceInfo(TfsClient.kt:35)
	at com.microsoft.tfs.TfsClient$Companion.getBasicWorkspaceInfo(TfsClient.kt:73)
	at com.microsoft.tfs.MainKt$initializeModel$2.invoke(Main.kt:94)
	at com.microsoft.tfs.MainKt$initializeModel$2.invoke(Main.kt)
	at com.jetbrains.rd.framework.impl.RdEndpoint$set$2.invoke(RdTask.kt:203)
	at com.jetbrains.rd.framework.impl.RdEndpoint$set$2.invoke(RdTask.kt:176)
	at com.jetbrains.rd.framework.impl.RdEndpoint.onWireReceived(RdTask.kt:226)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:31)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:14)
	at com.jetbrains.rd.util.threading.SingleThreadSchedulerBase$queue$1.run(SingleThreadScheduler.kt:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcClient.getBasicWorkspaceInfo(TfvcClient.java:328)
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcWorkspaceLocator.getPartialWorkspace(TfvcWorkspaceLocator.java:45)
	at com.microsoft.alm.plugin.idea.tfvc.extensions.TfvcRootChecker.lambda$isRoot$1(TfvcRootChecker.java:70)
	at com.microsoft.alm.plugin.idea.tfvc.ui.settings.EULADialog.executeWithGuard(EULADialog.java:229)
	at com.microsoft.alm.plugin.idea.tfvc.extensions.TfvcRootChecker.isRoot(TfvcRootChecker.java:66)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.lambda$getVcsRootFor$4(VcsRootDetectorImpl.java:183)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:56)
	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.java:54)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.getVcsRootFor(VcsRootDetectorImpl.java:182)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.scanForRootsAboveDir(VcsRootDetectorImpl.java:164)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.scanForRootsAboveDirs(VcsRootDetectorImpl.java:142)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.scanForRootsInContentRoots(VcsRootDetectorImpl.java:101)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.detect(VcsRootDetectorImpl.java:41)
	at com.intellij.openapi.vcs.roots.VcsRootErrorsFinder.find(VcsRootErrorsFinder.java:33)
	at com.intellij.openapi.vcs.roots.VcsRootProblemNotifier.scan(VcsRootProblemNotifier.java:205)
	at com.intellij.openapi.vcs.roots.VcsRootProblemNotifier.rescanAndNotifyIfNeeded(VcsRootProblemNotifier.java:73)
	at com.intellij.openapi.vcs.roots.VcsRootScanner.lambda$scheduleScan$2(VcsRootScanner.java:138)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:343)
	at com.intellij.openapi.vcs.roots.VcsRootScanner.lambda$scheduleScan$3(VcsRootScanner.java:137)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:241)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:388)
	at com.intellij.util.Alarm$Request.run(Alarm.java:377)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:223)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: com.jetbrains.rd.util.reactive.RdFault: /Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp: dlopen(/Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp, 0x0001): tried: '/Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), reason: java.lang.UnsatisfiedLinkError: /Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp: dlopen(/Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp, 0x0001): tried: '/Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e'))
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.microsoft.tfs.jni.internal.unix.macos.LibC.<clinit>(LibC.java:8)
	at com.microsoft.tfs.jni.internal.platformmisc.MacOsNativePlatformMisc.<clinit>(MacOsNativePlatformMisc.java:11)
	at com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.<init>(NativePlatformMisc.java:27)
	at com.microsoft.tfs.jni.PlatformMiscUtils.<init>(PlatformMiscUtils.java:22)
	at com.microsoft.tfs.jni.PlatformMiscUtils.<clinit>(PlatformMiscUtils.java:9)
	at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.makeDirectoryForVendorApplicationVersion(VersionedVendorFilesystemPersistenceStore.java:97)
	at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.<init>(VersionedVendorFilesystemPersistenceStore.java:60)
	at com.microsoft.tfs.core.config.persistence.DefaultPersistenceStoreProvider.<clinit>(DefaultPersistenceStoreProvider.java:42)
	at com.microsoft.tfs.TfsClient$Companion.tryLoadWorkspaceInfo(TfsClient.kt:35)
	at com.microsoft.tfs.TfsClient$Companion.getBasicWorkspaceInfo(TfsClient.kt:73)
	at com.microsoft.tfs.MainKt$initializeModel$2.invoke(Main.kt:94)
	at com.microsoft.tfs.MainKt$initializeModel$2.invoke(Main.kt)
	at com.jetbrains.rd.framework.impl.RdEndpoint$set$2.invoke(RdTask.kt:203)
	at com.jetbrains.rd.framework.impl.RdEndpoint$set$2.invoke(RdTask.kt:176)
	at com.jetbrains.rd.framework.impl.RdEndpoint.onWireReceived(RdTask.kt:226)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:31)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:14)
	at com.jetbrains.rd.util.threading.SingleThreadSchedulerBase$queue$1.run(SingleThreadScheduler.kt:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcClient.getBasicWorkspaceInfo(TfvcClient.java:326)
	... 44 more
Caused by: com.jetbrains.rd.util.reactive.RdFault: /Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp: dlopen(/Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp, 0x0001): tried: '/Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), reason: java.lang.UnsatisfiedLinkError: /Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp: dlopen(/Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp, 0x0001): tried: '/Users/burhan/Library/Caches/JNA/temp/jna15607678267468889707.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e'))
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.microsoft.tfs.jni.internal.unix.macos.LibC.<clinit>(LibC.java:8)
	at com.microsoft.tfs.jni.internal.platformmisc.MacOsNativePlatformMisc.<clinit>(MacOsNativePlatformMisc.java:11)
	at com.microsoft.tfs.jni.internal.platformmisc.NativePlatformMisc.<init>(NativePlatformMisc.java:27)
	at com.microsoft.tfs.jni.PlatformMiscUtils.<init>(PlatformMiscUtils.java:22)
	at com.microsoft.tfs.jni.PlatformMiscUtils.<clinit>(PlatformMiscUtils.java:9)
	at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.makeDirectoryForVendorApplicationVersion(VersionedVendorFilesystemPersistenceStore.java:97)
	at com.microsoft.tfs.core.persistence.VersionedVendorFilesystemPersistenceStore.<init>(VersionedVendorFilesystemPersistenceStore.java:60)
	at com.microsoft.tfs.core.config.persistence.DefaultPersistenceStoreProvider.<clinit>(DefaultPersistenceStoreProvider.java:42)
	at com.microsoft.tfs.TfsClient$Companion.tryLoadWorkspaceInfo(TfsClient.kt:35)
	at com.microsoft.tfs.TfsClient$Companion.getBasicWorkspaceInfo(TfsClient.kt:73)
	at com.microsoft.tfs.MainKt$initializeModel$2.invoke(Main.kt:94)
	at com.microsoft.tfs.MainKt$initializeModel$2.invoke(Main.kt)
	at com.jetbrains.rd.framework.impl.RdEndpoint$set$2.invoke(RdTask.kt:203)
	at com.jetbrains.rd.framework.impl.RdEndpoint$set$2.invoke(RdTask.kt:176)
	at com.jetbrains.rd.framework.impl.RdEndpoint.onWireReceived(RdTask.kt:226)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:31)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:14)
	at com.jetbrains.rd.util.threading.SingleThreadSchedulerBase$queue$1.run(SingleThreadScheduler.kt:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

	at com.jetbrains.rd.framework.RdTaskResult$Companion.read(TaskInterfaces.kt:23)
	at com.jetbrains.rd.framework.impl.RdCall.onWireReceived(RdTask.kt:102)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:31)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:14)
	at com.jetbrains.rd.util.threading.SynchronousScheduler.queue(SynchronousScheduler.kt:15)
	at com.jetbrains.rd.framework.MessageBroker.invoke(MessageBroker.kt:29)
	at com.jetbrains.rd.framework.MessageBroker.invoke$default(MessageBroker.kt:25)
	at com.jetbrains.rd.framework.MessageBroker.dispatch(MessageBroker.kt:96)
	at com.jetbrains.rd.framework.SocketWire$Base.readMsg(SocketWire.kt:151)
	at com.jetbrains.rd.framework.SocketWire$Base.receiverProc(SocketWire.kt:119)
	at com.jetbrains.rd.framework.SocketWire$Base.access$receiverProc(SocketWire.kt:65)
	at com.jetbrains.rd.framework.SocketWire$Base$1.invoke(SocketWire.kt:102)
	at com.jetbrains.rd.framework.SocketWire$Base$1.invoke(SocketWire.kt:65)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:29)
	at com.jetbrains.rd.util.reactive.OptProperty.set(Property.kt:33)
	at com.jetbrains.rd.framework.SocketWire$Server$thread$1.invoke(SocketWire.kt:369)
	at com.jetbrains.rd.framework.SocketWire$Server$thread$1.invoke(SocketWire.kt:338)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

## Rider Version:
```
JetBrains Rider 2022.1.1
Build #RD-221.5591.20, built on April 28, 2022
Licensed to Burhan Khalid
Subscription is active until October 30, 2022.
For educational use only.
Runtime version: 11.0.14.1+1-b2043.45 aarch64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
.NET 6.0.3
GC: G1 Young Generation, G1 Old Generation
Memory: 1504M
Cores: 10
Registry:
    indexing.enable.entity.provider.based.indexing=false
    ide.new.project.model.index.case.sensitivity=true
    rdclient.asyncActions=false

Non-Bundled Plugins:
    me.seclerp.rider.plugins.efcore (1.4.0)
    fr.socolin.application-insights-debug-log-viewer (1.4.1)
    com.markskelton.one-dark-theme (5.5.2)
    com.intellij.resharper.StructuredLogging (2022.1.0.188)
    com.intellij.resharper.HeapAllocationsViewer (2022.1.0)
    com.intellij.ideolog (203.0.28.1)
    com.gmike.visual-studio-2019-dark (1.5.3)
    io.snyk.snyk-intellij-plugin (2.4.30)
    com.intellij.resharper.azure (3.50.0.1413-2022.1)
    IdeaVIM (1.10.2)
    org.sonarlint.idea (6.7.0.45926)
    com.microsoft.vso.idea (1.162.0)
    com.mallowigi (64.0.0)
    Abc.MoqComplete.Rider (2022.1.0.1)
```

Is there a version that has arm support?

**Comment by ForNeVeR** [comment]
Please try installing [the latest version of team-explorer-everywhere](https://github.com/JetBrains/team-explorer-everywhere/releases) command line client (which should add M1 support) and disabling the reactive TFVC client in the settings,

**Comment by bk-tfo** [comment]
Thank you! That has solved the problem. I also found [this bug](https://youtrack.jetbrains.com/issue/RIDER-57683/Apple-M1-azure-devops-tfvc-support) in YouTrack for the same issue.
