### ISSUE TITLE
getAuthenticationInfoAsync failed

### ISSUE THREAD

**Issue by cglaeser** [microsoft/azure-devops-intellij#501]
getAuthenticationInfoAsync failed

com.microsoft.alm.client.model.VssResourceNotFoundException: API resource location f83735dc-483f-4238-a291-d45f6080a9af is not registered on https://app.vssps.visualstudio.com. HTTP 400 Bad Request
	at com.microsoft.alm.client.AlmHttpClientBase.createTarget(AlmHttpClientBase.java:138)
	at com.microsoft.alm.client.AlmHttpClientBase.createRequest(AlmHttpClientBase.java:463)
	at com.microsoft.alm.client.AlmHttpClientBase.createRequest(AlmHttpClientBase.java:334)
	at com.microsoft.visualstudio.services.account.AccountHttpClient.getMyProfile(AccountHttpClient.java:49)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfo(VsoAuthInfoProvider.java:123)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfoAsync(VsoAuthInfoProvider.java:95)
	at com.microsoft.alm.plugin.authentication.VsoAuthenticationProvider.authenticateAsync(VsoAuthenticationProvider.java:66)
	at com.microsoft.alm.plugin.authentication.AuthHelper.getAuthenticationInfoSynchronously(AuthHelper.java:59)
	at com.microsoft.alm.plugin.idea.git.extensions.TfGitHttpAuthDataProvider.getAuthData(TfGitHttpAuthDataProvider.java:124)
	at git4idea.remote.GitHttpAuthDataProvider.getAuthData(GitHttpAuthDataProvider.java:36)
	at git4idea.commands.GitHttpGuiAuthenticator$ExtensionAdapterProvider.getDataForKnownLogin(GitHttpGuiAuthenticator.java:309)
	at git4idea.commands.GitHttpGuiAuthenticator.lambda$askPassword$1(GitHttpGuiAuthenticator.java:106)
	at git4idea.commands.GitHttpGuiAuthenticator.lambda$acquireData$2(GitHttpGuiAuthenticator.java:143)
	at com.intellij.externalProcessAuthHelper.PassthroughAuthenticationGate.waitAndCompute(AuthenticationGates.kt:52)
	at git4idea.commands.GitHttpGuiAuthenticator.acquireData(GitHttpGuiAuthenticator.java:140)
	at git4idea.commands.GitHttpGuiAuthenticator.askPassword(GitHttpGuiAuthenticator.java:106)
	at git4idea.commands.GitHttpAuthService$InternalRequestHandlerDelegate.lambda$handleInput$0(GitHttpAuthService.java:73)
	at git4idea.commands.GitHttpAuthService.getDefaultValueIfCancelled(GitHttpAuthService.java:89)
	at git4idea.commands.GitHttpAuthService$InternalRequestHandlerDelegate.handleInput(GitHttpAuthService.java:72)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jetbrains.ide.XmlRpcServerImpl.invoke(XmlRpcServerImpl.java:184)
	at org.jetbrains.ide.XmlRpcServerImpl.invokeHandler(XmlRpcServerImpl.java:145)
	at org.jetbrains.ide.XmlRpcServerImpl.process(XmlRpcServerImpl.java:105)
	at org.jetbrains.ide.XmlRpcServerImpl$XmlRpcRequestHandler.process(XmlRpcServerImpl.java:63)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:21)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$2.test(DelegatingHttpRequestHandler.kt:35)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$2.test(DelegatingHttpRequestHandler.kt:16)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.lambda$findFirstSafe$0(ExtensionProcessingHelper.java:46)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:56)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.findFirstSafe(ExtensionProcessingHelper.java:46)
	at com.intellij.openapi.extensions.ExtensionPointName.findFirstSafe(ExtensionPointName.java:50)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.kt:34)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:15)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:11)
	at org.jetbrains.io.SimpleChannelInboundHandlerAdapter.channelRead0(SimpleChannelInboundHandlerAdapter.java:21)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.jetbrains.io.PortUnificationServerHandler.decode(PortUnificationServerHandler.java:129)
	at org.jetbrains.io.PortUnificationServerHandler.messageReceived(PortUnificationServerHandler.java:76)
	at org.jetbrains.io.Decoder.channelRead(Decoder.java:24)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.ws.rs.BadRequestException: HTTP 400 Bad Request
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1053)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:859)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:75)
	at org.glassfish.jersey.client.JerseyInvocation$2.completed(JerseyInvocation.java:816)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:203)
	at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:61)
	at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:154)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
	at org.glassfish.jersey.client.ClientRuntime$2.response(ClientRuntime.java:154)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:480)
	at org.glassfish.jersey.client.ClientRuntime.lambda$null$3(ClientRuntime.java:163)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
	at org.glassfish.jersey.client.ClientRuntime.lambda$createRunnableForAsyncProcessing$4(ClientRuntime.java:139)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more

**Comment by wolfie82** [comment]
This kind of looks like #497.  I believe the only way to fix it is to either rebuild the plugin, or update it to support a better auth mechanism.
