### ISSUE TITLE
Exception when activating TFVC on Macbook

### ISSUE THREAD

**Issue by VijayDeyTR** [microsoft/azure-devops-intellij#525]
Hi,

I use macbook M1, installed the latest version of this plugin, but get below exception when using it.

java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.jetbrains.rd.util.reactive.RdFault: Could not initialize class com.microsoft.tfs.core.config.persistence.DefaultPersistenceStoreProvider, reason: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.tfs.core.config.persistence.DefaultPersistenceStoreProvider
	at com.microsoft.tfs.TfsClient$Companion.tryLoadWorkspaceInfo(TfsClient.kt:35)
	at com.microsoft.tfs.TfsClient$Companion.getBasicWorkspaceInfo(TfsClient.kt:73)
	at com.microsoft.tfs.MainKt$initializeModel$2.invoke(Main.kt:94)
	at com.microsoft.tfs.MainKt$initializeModel$2.invoke(Main.kt)
	at com.jetbrains.rd.framework.impl.RdEndpoint$set$2.invoke(RdTask.kt:203)
	at com.jetbrains.rd.framework.impl.RdEndpoint$set$2.invoke(RdTask.kt:176)
	at com.jetbrains.rd.framework.impl.RdEndpoint.onWireReceived(RdTask.kt:226)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:31)
	at com.jetbrains.rd.framework.MessageBroker$invoke$1.invoke(MessageBroker.kt:14)
	at com.jetbrains.rd.util.threading.SingleThreadSchedulerBase$queue$1.run(SingleThreadScheduler.kt:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by ForNeVeR** [comment]
`java.lang.NoClassDefFoundError` means the class in question failed to initialize, and the relevant exception should've been logged somewhere earlier.

I think this has been fixed by #513, but please provide more logs (look for `ExceptionInInitializerError`) to figure it out.
