### ISSUE TITLE
java.lang.IllegalStateException on WebStorm

### ISSUE THREAD

**Issue by internetbird** [microsoft/azure-devops-intellij#539]
Hi,
I've upgraded to the latest WebStorm (Version 2022.3 Build #WS-223.7571.168) and Azure DevOps plugin (Version 1.162.1).
When I open my project I get the following error:

**java.lang.IllegalStateException: Calling invokeAndWait from read-action leads to possible deadlock.**

Here is the full stacktrace:

java.lang.IllegalStateException: Calling invokeAndWait from read-action leads to possible deadlock.
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:417)
	at com.microsoft.alm.plugin.external.reactive.ReactiveTfvcClientHolder.ensureEulaAccepted(ReactiveTfvcClientHolder.java:76)
	at com.microsoft.alm.plugin.external.reactive.ReactiveTfvcClientHolder.getClient(ReactiveTfvcClientHolder.java:53)
	at com.microsoft.alm.plugin.idea.tfvc.core.ReactiveTfvcClient.lambda$getBasicWorkspaceInfoAsync$25(ReactiveTfvcClient.java:203)
	at com.microsoft.alm.plugin.idea.tfvc.core.ReactiveTfvcClient.traceTime(ReactiveTfvcClient.java:55)
	at com.microsoft.alm.plugin.idea.tfvc.core.ReactiveTfvcClient.getBasicWorkspaceInfoAsync(ReactiveTfvcClient.java:203)
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcClient.getBasicWorkspaceInfo(TfvcClient.java:326)
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcWorkspaceLocator.getPartialWorkspace(TfvcWorkspaceLocator.java:45)
	at com.microsoft.alm.plugin.idea.tfvc.extensions.TfvcRootChecker.lambda$isRoot$1(TfvcRootChecker.java:70)
	at com.microsoft.alm.plugin.idea.tfvc.ui.settings.EULADialog.executeWithGuard(EULADialog.java:229)
	at com.microsoft.alm.plugin.idea.tfvc.extensions.TfvcRootChecker.isRoot(TfvcRootChecker.java:66)
	at com.intellij.openapi.vcs.VcsRootChecker.isRoot(VcsRootChecker.java:31)
	at com.intellij.openapi.vcs.VcsRootChecker.validateRoot(VcsRootChecker.java:49)
	at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.checkMappedRoot(NewMappings.java:423)
	at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.lambda$findDirectMappingFor$8(NewMappings.java:365)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:873)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.findDirectMappingFor(NewMappings.java:357)
	at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.collectMappedRoots(NewMappings.java:312)
	at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.updateMappedRoots(NewMappings.java:224)
	at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.activateActiveVcses(NewMappings.java:110)
	at com.intellij.openapi.vcs.impl.ProjectLevelVcsManagerImpl$ActivateVcsesStartupActivity.runActivity(ProjectLevelVcsManagerImpl.java:936)
	at com.intellij.openapi.vcs.impl.VcsInitialization.lambda$runActivities$3(VcsInitialization.java:157)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:241)
	at com.intellij.openapi.vcs.impl.VcsInitialization.runActivities(VcsInitialization.java:157)
	at com.intellij.openapi.vcs.impl.VcsInitialization.runInitStep(VcsInitialization.java:141)
	at com.intellij.openapi.vcs.impl.VcsInitialization.execute(VcsInitialization.java:112)
	at com.intellij.openapi.vcs.impl.VcsInitialization$1.run(VcsInitialization.java:68)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:425)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:476)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ForNeVeR** [comment]
For now, maybe you'll be able to work around the issue by turning off the reactive client in the plugin settings.
