### ISSUE TITLE
idea 启动时报这个错误

### ISSUE THREAD

**Issue by daniubi** [microsoft/azure-devops-intellij#556]
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcClient.getBasicWorkspaceInfo(TfvcClient.java:328)
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcWorkspaceLocator.getPartialWorkspace(TfvcWorkspaceLocator.java:45)
	at com.microsoft.alm.plugin.idea.tfvc.extensions.TfvcRootChecker.lambda$isRoot$1(TfvcRootChecker.java:70)
	at com.microsoft.alm.plugin.idea.tfvc.ui.settings.EULADialog.executeWithGuard(EULADialog.java:255)
	at com.microsoft.alm.plugin.idea.tfvc.extensions.TfvcRootChecker.isRoot(TfvcRootChecker.java:66)
	at com.intellij.openapi.vcs.VcsRootChecker.isRoot(VcsRootChecker.java:31)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.detectVcsRootBy(VcsRootDetectorImpl.java:229)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.lambda$getVcsRootFor$4(VcsRootDetectorImpl.java:220)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.kt:57)
	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.kt:57)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.getVcsRootFor(VcsRootDetectorImpl.java:219)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.scanForRootsAboveDir(VcsRootDetectorImpl.java:171)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.scanForRootsAboveDirs(VcsRootDetectorImpl.java:149)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.scanForRootsInContentRoots(VcsRootDetectorImpl.java:103)
	at com.intellij.openapi.vcs.roots.VcsRootDetectorImpl.detect(VcsRootDetectorImpl.java:43)
	at com.intellij.openapi.vcs.roots.VcsRootErrorsFinder.find(VcsRootErrorsFinder.java:35)
	at com.intellij.openapi.vcs.roots.VcsRootProblemNotifier.scan(VcsRootProblemNotifier.java:213)
	at com.intellij.openapi.vcs.roots.VcsRootProblemNotifier.rescanAndNotifyIfNeeded(VcsRootProblemNotifier.java:74)
	at com.intellij.openapi.vcs.roots.VcsRootScanner.lambda$scheduleScan$2(VcsRootScanner.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:361)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:339)
	at com.intellij.openapi.vcs.roots.VcsRootScanner.lambda$scheduleScan$3(VcsRootScanner.java:141)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:249)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:365)
	at com.intellij.util.Alarm$Request.run(Alarm.java:354)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at com.microsoft.alm.plugin.idea.tfvc.core.TfvcClient.getBasicWorkspaceInfo(TfvcClient.java:326)
	... 46 more
Caused by: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2478)
	at com.microsoft.tfs.connector.ReactiveClientConnection$queueFutureAsync$1.invoke(ReactiveClientConnection.kt:138)
	at com.microsoft.tfs.connector.ReactiveClientConnection$queueFutureAsync$1.invoke(ReactiveClientConnection.kt:18)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.destruct(RLifetime.kt:276)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.terminate(RLifetime.kt:262)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.destruct(RLifetime.kt:282)
	at com.jetbrains.rd.util.lifetime.LifetimeDefinition.terminate(RLifetime.kt:262)
	at com.microsoft.alm.plugin.external.reactive.ReactiveTfvcClientHost$1.notifyProcessTerminated(ReactiveTfvcClientHost.java:99)
	at com.intellij.execution.process.BaseProcessHandler.onOSProcessTerminated(BaseProcessHandler.java:61)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:186)
	at com.intellij.execution.process.BaseOSProcessHandler$1.lambda$startNotified$0(BaseOSProcessHandler.java:84)
	at com.intellij.execution.process.ProcessWaitFor.lambda$new$0(ProcessWaitFor.java:45)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.execution.process.ProcessWaitFor.lambda$new$1(ProcessWaitFor.java:23)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 7 more

**Comment by GemiW0609** [comment]
I have the same issue, maybe you should to follow this:
1.Install OpenJDK 11.
2.Set JAVA_HOME to the location of JDK 11.
https://learn.microsoft.com/en-us/java/openjdk/download
I have fix now.
