### ISSUE TITLE
Upgrading plugin to 1.162.2  in Rider breaks Settings/Plugins dialog

### ISSUE THREAD

**Issue by kevkov** [microsoft/azure-devops-intellij#567]
Dialog does not display. Logs have this

```
2023-09-11 18:48:18,928 [  52887] SEVERE - #c.i.o.o.e.ConfigurableWrapper - JetBrains Rider 2023.2.1  Build #RD-232.9559.61
2023-09-11 18:48:18,928 [  52887] SEVERE - #c.i.o.o.e.ConfigurableWrapper - JDK: 17.0.8; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-09-11 18:48:18,928 [  52887] SEVERE - #c.i.o.o.e.ConfigurableWrapper - OS: Mac OS X
2023-09-11 18:48:18,929 [  52888] SEVERE - #c.i.o.o.e.ConfigurableWrapper - Plugin to blame: Azure Toolkit for Rider version: 3.50.0.1678-2023.2
2023-09-11 18:48:18,974 [  52933] SEVERE - #c.i.i.a.ShowSettingsUtilImpl - null
java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at com.microsoft.intellij.configuration.AzureRiderSettings.getAzuriteExecutable(AzureRiderSettings.kt:140)
	at org.jetbrains.plugins.azure.storage.azurite.AzuriteConfigurationPanel$createPanel$1$1$1.invoke(AzuriteConfigurationPanel.kt:59)
	at org.jetbrains.plugins.azure.storage.azurite.AzuriteConfigurationPanel$createPanel$1$1$1.invoke(AzuriteConfigurationPanel.kt:58)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:58)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:45)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:20)
	at org.jetbrains.plugins.azure.storage.azurite.AzuriteConfigurationPanel$createPanel$1$1.invoke(AzuriteConfigurationPanel.kt:58)
	at org.jetbrains.plugins.azure.storage.azurite.AzuriteConfigurationPanel$createPanel$1$1.invoke(AzuriteConfigurationPanel.kt:57)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.indent(PanelImpl.kt:398)
```

Disabling the plugin fixes the issue.

MacOS Ventura 13.5.2

**Comment by ForNeVeR** [comment]
This is seemingly an issue of [the Azure Toolkit for Rider](https://github.com/JetBrains/azure-tools-for-intellij), not Azure DevOps. Please report there (unfortunately, I have no permission to transfer the issue there myself).

**Comment by kevkov** [comment]
Apologies, got distracted and clicked the wrong link.
