### ISSUE TITLE
Can't authenticate - getAuthenticationInfoAsync failed

### ISSUE THREAD

**Issue by niander** [microsoft/azure-devops-intellij#570]
After initiating the device code login and having successful confirmation message in the browser. The plugin fails with the following error:

```
   getAuthenticationInfoAsync failed
   
   java.lang.Error: java.io.IOException: HTTP request failed with code 400: {"$id":"1","innerException":null,"message":"FullScopePatPolicyViolation","typeName":"Microsoft.VisualStudio.Services.DelegatedAuthorization.SessionTokenCreateException, Microsoft.VisualStudio.Services.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"SessionTokenCreateException","errorCode":0,"eventId":3000}

	at com.microsoft.alm.auth.pat.VsoAzureAuthority.generatePersonalAccessToken(VsoAzureAuthority.java:79)
	at com.microsoft.alm.auth.pat.VstsPatAuthenticator$1.doRetrieve(VstsPatAuthenticator.java:195)
	at com.microsoft.alm.auth.pat.VstsPatAuthenticator$1.doRetrieve(VstsPatAuthenticator.java:157)
	at com.microsoft.alm.auth.BaseAuthenticator$SecretRetriever.retrieve(BaseAuthenticator.java:268)
	at com.microsoft.alm.auth.pat.VstsPatAuthenticator.getToken(VstsPatAuthenticator.java:202)
	at com.microsoft.alm.auth.pat.VstsPatAuthenticator.getPersonalAccessToken(VstsPatAuthenticator.java:142)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfo(VsoAuthInfoProvider.java:138)
	at com.microsoft.alm.plugin.authentication.facades.VsoAuthInfoProvider.getAuthenticationInfoAsync(VsoAuthInfoProvider.java:95)
	at com.microsoft.alm.plugin.authentication.VsoAuthenticationProvider.authenticateAsync(VsoAuthenticationProvider.java:66)
	at com.microsoft.alm.plugin.authentication.AuthHelper.getAuthenticationInfoSynchronously(AuthHelper.java:59)
	at com.microsoft.alm.plugin.idea.git.extensions.TfGitHttpAuthDataProvider.getAuthData(TfGitHttpAuthDataProvider.java:124)
	at git4idea.commands.GitHttpGuiAuthenticator$ExtensionAdapterProvider.getData(GitHttpGuiAuthenticator.java:325)
	at git4idea.commands.GitHttpGuiAuthenticator.lambda$acquireData$2(GitHttpGuiAuthenticator.java:159)
	at com.intellij.externalProcessAuthHelper.RestrictingAuthenticationGate.waitAndCompute(AuthenticationGates.kt:26)
	at git4idea.commands.GitHttpGuiAuthenticator.acquireData(GitHttpGuiAuthenticator.java:156)
	at git4idea.commands.GitHttpGuiAuthenticator.askUsername(GitHttpGuiAuthenticator.java:135)
	at git4idea.commands.GitHttpAuthService$AuthAppHandler.handleInput(GitHttpAuthService.kt:62)
	at git4idea.commands.GitHttpAuthService.handleRequest(GitHttpAuthService.kt:49)
	at git4idea.commands.GitHttpAuthService.handleRequest(GitHttpAuthService.kt:35)
	at com.intellij.externalProcessAuthHelper.ExternalProcessHandlerService.invokeHandler$intellij_platform_externalProcessAuthHelper(ExternalProcessHandlerService.kt:99)
	at com.intellij.externalProcessAuthHelper.ExternalProcessRest.runHandler$lambda$3(ExternalProcessHandlerService.kt:168)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.externalProcessAuthHelper.ExternalProcessRest.runHandler(ExternalProcessHandlerService.kt:168)
	at com.intellij.externalProcessAuthHelper.ExternalProcessRest.execute$lambda$1(ExternalProcessHandlerService.kt:142)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: HTTP request failed with code 400: {"$id":"1","innerException":null,"message":"FullScopePatPolicyViolation","typeName":"Microsoft.VisualStudio.Services.DelegatedAuthorization.SessionTokenCreateException, Microsoft.VisualStudio.Services.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"SessionTokenCreateException","errorCode":0,"eventId":3000}

	at com.microsoft.alm.helpers.HttpClientImpl.ensureOK(HttpClientImpl.java:41)
	at com.microsoft.alm.helpers.HttpClientImpl.getPostResponseText(HttpClientImpl.java:186)
	at com.microsoft.alm.auth.pat.VsoAzureAuthority.generatePersonalAccessToken(VsoAzureAuthority.java:69)
	... 39 more
```

**Comment by connorjs** [comment]
I recommend closing issues related to `FullScopePatPolicyViolation` in favor of #481 which, at time of writing, has the most up votes. Let's focus the discussion there.
