### ISSUE TITLE
Plugin don't work with IntelliJ 2024.* version

### ISSUE THREAD

**Issue by ahweis** [microsoft/azure-devops-intellij#578]
After upgrading IntelliJ to 2024.1 this plugin don't work anymore, it is not possible to create pullrequests.

The error reported in IntelliJ:

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.microsoft.alm.plugin.idea.common.ui.common.ToolbarToggleButton' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.microsoft.vso.idea]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by ahweis** [comment]
#575 Related

**Comment by ForNeVeR** [comment]
This exception cannot cause any issues. Could you please be more specific?

**Comment by ahweis** [comment]
It is not possible to create a new pull request, nothing happens when clicking on the "plus" button or use the "Alt" + "Insert" short cut to open the "Create Pull Request" dialog.
