### ISSUE TITLE
Azure devops plugin error

### ISSUE THREAD

**Issue by PGTBoos** [microsoft/azure-devops-intellij#594]
I had this exception with the azure plugin of devops in webstorm today, webstorm made it clear it wasn't their fault and I had to report it here, so here it goes.

java.lang.Throwable: com.microsoft.alm.plugin.context.ServerContextManager$Holder <clinit> requests com.microsoft.alm.plugin.idea.common.settings.TeamServicesSecrets instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1588)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1557)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:746)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:690)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:23)
	at com.microsoft.alm.plugin.idea.common.settings.TeamServicesSecrets.getInstance(TeamServicesSecrets.java:23)
	at com.microsoft.alm.plugin.idea.common.settings.TeamServicesSettingsService.restoreServerContexts(TeamServicesSettingsService.java:75)
	at com.microsoft.alm.plugin.idea.common.services.ServerContextStoreImpl.restoreServerContexts(ServerContextStoreImpl.java:25)
	at com.microsoft.alm.plugin.context.ServerContextManager.restoreFromSavedState(ServerContextManager.java:178)
	at com.microsoft.alm.plugin.context.ServerContextManager.<init>(ServerContextManager.java:71)
	at com.microsoft.alm.plugin.context.ServerContextManager$Holder.<clinit>(ServerContextManager.java:55)
	at com.microsoft.alm.plugin.context.ServerContextManager.getInstance(ServerContextManager.java:79)
	at com.microsoft.alm.plugin.operations.Operation.getServerContext(Operation.java:164)
	at com.microsoft.alm.plugin.operations.BuildStatusLookupOperation.doWork(BuildStatusLookupOperation.java:149)
	at com.microsoft.alm.plugin.operations.OperationExecutor$1.run(OperationExecutor.java:56)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by tranbane** [comment]
Same problem.  Please advise.

**Comment by mballintijn** [comment]
Also same problem. Please address ASAP.

**Comment by bobonov** [comment]
same error as #589

**Comment by seaare42** [comment]
Exact same problem.

**Comment by Jonatha1983** [comment]
Hello @seaare42    @bobonov  @mballintijn   @tranbane    @PGTBoos 

I noticed you're experiencing some issues with the Azure DevOps plugin for IntelliJ. I just wanted to let you know about an alternative that might help—my [AZD IntelliJ Plugin](https://plugins.jetbrains.com/plugin/18970-azd-azure-devops-integration).

Although it's not free, you can benefit from a 10-day free trial to see if it suits your needs. You can read reviews and see what people are saying about it on the [JetBrains Marketplace](https://plugins.jetbrains.com/plugin/18970-azd-azure-devops-integration) and in this JetBrains blog post:

[Plugin Spotlight on JetBrains Marketplace AZD Plugin](https://blog.jetbrains.com/platform/2024/04/plugin-spotlight-on-jetbrains-marketplace/#azd-plugin)

For more information, check out the [documentation](https://edgafner.github.io/azd.html). If you have bugs to report or feature requests, feel free to use the [issue tracker](https://github.com/edgafner/dorkag/issues).

Cheers,

Jonathan

**Comment by abnerh69sparq** [comment]
Same here:
1.162.2
java.lang.Throwable: com.microsoft.alm.plugin.context.ServerContextManager$Holder <clinit> requests com.microsoft.alm.plugin.idea.common.settings.TeamServicesSecrets instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1588)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1557)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:746)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:690)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:23)
	at com.microsoft.alm.plugin.idea.common.settings.TeamServicesSecrets.getInstance(TeamServicesSecrets.java:23)
	at com.microsoft.alm.plugin.idea.common.settings.TeamServicesSettingsService.restoreServerContexts(TeamServicesSettingsService.java:75)
	at com.microsoft.alm.plugin.idea.common.services.ServerContextStoreImpl.restoreServerContexts(ServerContextStoreImpl.java:25)
	at com.microsoft.alm.plugin.context.ServerContextManager.restoreFromSavedState(ServerContextManager.java:178)
	at com.microsoft.alm.plugin.context.ServerContextManager.<init>(ServerContextManager.java:71)
	at com.microsoft.alm.plugin.context.ServerContextManager$Holder.<clinit>(ServerContextManager.java:55)
	at com.microsoft.alm.plugin.context.ServerContextManager.getInstance(ServerContextManager.java:79)
	at com.microsoft.alm.plugin.operations.Operation.getServerContext(Operation.java:164)
	at com.microsoft.alm.plugin.operations.BuildStatusLookupOperation.doWork(BuildStatusLookupOperation.java:149)
	at com.microsoft.alm.plugin.operations.OperationExecutor$1.run(OperationExecutor.java:56)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by bijustrada360** [comment]
same issue with Rider on Ubuntu 22/04

**Comment by jimlester** [comment]
Same issue on DataGrip 2024.3.1 for Mac.
