### ISSUE TITLE
Is the project alive?

### ISSUE THREAD

**Issue by emartynov** [microsoft/azure-devops-intellij#596]
Hi people,

I see that last release was 2023. Also looks like last commit landed 10 months ago.
Is this project alive still?

Kind Regards,
Eugen

**Comment by snarum** [comment]
Mine crashes brutally on Rider 2024.3, so I would say it's about time to either revive or bury. Sad if it's dropped though as I find it quite useful.

**Comment by ForNeVeR** [comment]
It still works in Rider 2024.3. Cannot confirm any crashes. The plugin is still supported and works in the latest versions of the IDEs.

**Comment by snarum** [comment]
I get this message on startup. I have tried to invalidate all caches. Didn't get this on 2024.2

```
java.lang.Throwable: com.microsoft.alm.plugin.context.ServerContextManager$Holder <clinit> requests com.microsoft.alm.plugin.idea.common.settings.TeamServicesSecrets instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1586)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1555)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:751)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:695)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:23)
	at com.microsoft.alm.plugin.idea.common.settings.TeamServicesSecrets.getInstance(TeamServicesSecrets.java:23)
	at com.microsoft.alm.plugin.idea.common.settings.TeamServicesSettingsService.restoreServerContexts(TeamServicesSettingsService.java:75)
	at com.microsoft.alm.plugin.idea.common.services.ServerContextStoreImpl.restoreServerContexts(ServerContextStoreImpl.java:25)
	at com.microsoft.alm.plugin.context.ServerContextManager.restoreFromSavedState(ServerContextManager.java:178)
	at com.microsoft.alm.plugin.context.ServerContextManager.<init>(ServerContextManager.java:71)
	at com.microsoft.alm.plugin.context.ServerContextManager$Holder.<clinit>(ServerContextManager.java:55)
	at com.microsoft.alm.plugin.context.ServerContextManager.getInstance(ServerContextManager.java:79)
	at com.microsoft.alm.plugin.operations.Operation.getServerContext(Operation.java:164)
	at com.microsoft.alm.plugin.operations.BuildStatusLookupOperation.doWork(BuildStatusLookupOperation.java:149)
	at com.microsoft.alm.plugin.operations.OperationExecutor$1.run(OperationExecutor.java:56)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
