### ISSUE TITLE
Exception in plugin Azure DevOps (1.162.2) in Rider 2024.3 on Ubuntu 22.04

### ISSUE THREAD

**Issue by bijustrada360** [microsoft/azure-devops-intellij#597]
java.lang.Throwable: com.microsoft.alm.plugin.context.ServerContextManager$Holder <clinit> requests com.microsoft.alm.plugin.idea.common.settings.TeamServicesSecrets instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1586)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1555)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:751)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:695)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:23)
	at com.microsoft.alm.plugin.idea.common.settings.TeamServicesSecrets.getInstance(TeamServicesSecrets.java:23)
	at com.microsoft.alm.plugin.idea.common.settings.TeamServicesSettingsService.restoreServerContexts(TeamServicesSettingsService.java:75)
	at com.microsoft.alm.plugin.idea.common.services.ServerContextStoreImpl.restoreServerContexts(ServerContextStoreImpl.java:25)
	at com.microsoft.alm.plugin.context.ServerContextManager.restoreFromSavedState(ServerContextManager.java:178)
	at com.microsoft.alm.plugin.context.ServerContextManager.<init>(ServerContextManager.java:71)
	at com.microsoft.alm.plugin.context.ServerContextManager$Holder.<clinit>(ServerContextManager.java:55)
	at com.microsoft.alm.plugin.context.ServerContextManager.getInstance(ServerContextManager.java:79)
	at com.microsoft.alm.plugin.operations.Operation.getServerContext(Operation.java:164)
	at com.microsoft.alm.plugin.operations.BuildStatusLookupOperation.doWork(BuildStatusLookupOperation.java:149)
	at com.microsoft.alm.plugin.operations.OperationExecutor$1.run(OperationExecutor.java:56)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by jfranki** [comment]
Same on Windows 11 23H2 at every startup. The plugin is unusable.

Azure DevOps v1.162.2
Jetbrains Rider v2024.3.2
